### ISSUE TITLE
nav: left component nav behavior is still not perfect

### ISSUE THREAD

**Issue by mackelito** [angular/material.angular.io#1013]
#### Documentation Feedback
https://material.angular.io/components/tooltip/overview
works fine but it's missing from the left side navigation.. it's not actually missing but you need to scroll down the content as well to see it...

https://user-images.githubusercontent.com/598463/121891905-598b1e80-cd1c-11eb-9ff0-9e54d9e41a89.mp4

**Affected documentation page:** Insert a link to the affected page on material.angular.io
https://material.angular.io/components/tooltip/overview

**Comment by Splaktar** [comment]
This was also reported in https://github.com/angular/material.angular.io/issues/857 and was improved upon in PR https://github.com/angular/material.angular.io/pull/978.


https://user-images.githubusercontent.com/3506071/122137631-12338980-ce13-11eb-917b-e9b59e934868.mov

The situation is considerably improved from what it was previously. If you scroll again after hitting the bottom, it will show all of the entries (it did not previously).
