### ISSUE TITLE
Bug: Stackblitz examples broken on stackblitz.com

### ISSUE THREAD

**Issue by joelkesler** [angular/material.angular.io#1049]
When I click the "Edit <example name> in Stackblitz button on the Angular Material site, the resulting Stackblitz link will not build

Examples from the Mat Table examples page: https://material.angular.io/components/table/examples

![image](https://user-images.githubusercontent.com/303329/130293057-4f8ad9a8-7636-42a6-b680-50d43d04edcb.png)

![image](https://user-images.githubusercontent.com/303329/130293074-5d1dbd91-7ec3-4537-8e14-61dff723bede.png)

**Comment by jelbourn** [comment]
Just had this issue brought to my attention today. We've known about this issue for a while- it happens right after we publish a release to npm because some complicated reasons involving StackBlitz's npm cache and `ngcc`. There's not much we can do about it on the Angular side, but we think that it will go away with v13 because we're changing the way that Angular packages are built.

**Comment by Splaktar** [comment]
This should be fixed in 
- https://github.com/angular/material.angular.io/commit/e190dc4d86d4b595d2350d7405dfe4ae5963d849
- https://github.com/angular/material.angular.io/commit/f41506ac505206763b384808e196a6bb2459d1d5

Since we disabled Ivy in StackBlitz due to `ngcc` issues like those above.

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material.angular.io/pull/1077.

**Comment by svaughtAA** [comment]
Can this be reopened? I can't get any of the angular examples to load in stackblitz, they just get stuck on "Booting WebContainer"

![image](https://user-images.githubusercontent.com/97050363/148789644-d319b118-6cf2-459a-8a27-b4d28ff1d675.png)

**Comment by Splaktar** [comment]
@svaughtAA there are a number of issues open against StackBlitz that we're tracking related to Angular v13 support. This specific issue (pre-v13) is resolved. Please feel free to open a new issue.
