### ISSUE TITLE
Unable to open samples

### ISSUE THREAD

**Issue by bgauvey** [angular/material.angular.io#105]
When opening https://material.angular.io/guide/leashed-in an exception is created. Same exception encountered with the material2-app sample as well.

TypeError: Cannot read property 'document' of undefined

OS: WINDOWS 10 Pro
Browser: Chrome v56.0.2924.87

**Comment by ruffiem** [comment]
You can't open it because it doesn't exist... yet.

**Comment by kara** [comment]
@bgauvey This is the correct link: https://github.com/kara/leashed-in

One of our docs site scripts copied the wrong domain, but it should be fixed soon on the main site.
