### ISSUE TITLE
Material docs are currently defaulting to showing v13 -next, v12 docs inaccessible

### ISSUE THREAD

**Issue by tstackhouse** [angular/material.angular.io#1051]
The version switcher in the menu bar is defaulting to v13-next, and selecting v12 only refreshes the page, it does not actually switch to v12, not does directly attempting to navigate to https://v12.material.angular.io/ function, as there is no dns entry for that domain.

**Comment by Splaktar** [comment]
This is fixed on https://material.angular.io/ now that v13 has been released.

**Comment by tstackhouse** [comment]
Thanks!
