### ISSUE TITLE
All stackblitz examples are not opening

### ISSUE THREAD

**Issue by encounter12** [angular/material.angular.io#1076]
When I click on all of the Stackblitz examples on Angular Material Page: https://material.angular.io/components/ they are not opening. The following JSON appears:

```json
{
   "status":422,
   "response":{
      "req":{
         "method":"PUT",
         "url":"https://services.stackblitz.com/api/resolver",
         "data":{
            "dependencies":{
               "@angular/cdk":"12.2.7",
               "@angular/animations":"^12.0.0",
               "@angular/common":"^12.0.0",
               "@angular/compiler":"^12.0.0",
               "@angular/core":"^12.0.0",
               "@angular/forms":"^12.0.0",
               "@angular/material":"12.2.7",
               "@angular/material-moment-adapter":"12.2.7",
               "@angular/platform-browser":"^12.0.0",
               "@angular/platform-browser-dynamic":"^12.0.0",
               "@angular/router":"^12.0.0",
               "moment":"^2.29.1",
               "rxjs":"^6.6.7",
               "tslib":"^2.2.0",
               "zone.js":"^0.11.4"
            }
         },
         "headers":{
            "content-type":"application/json"
         }
      },
      "header":{
         "content-type":"application/json; charset=utf-8",
         "content-length":"77",
         "connection":"close",
         "date":"Mon, 27 Sep 2021 16:11:23 GMT",
         "etag":"W/\"4d-Ku6vz+VQb4slIxgp4ZOCyei2SOg\"",
         "server":"Stackblitz Services",
         "vary":"Origin",
         "x-cache":"Error from cloudfront",
         "via":"1.1 aa0280f933863b8ffd5ff636330f4170.cloudfront.net (CloudFront)",
         "x-amz-cf-pop":"HIO50-C2",
         "x-amz-cf-id":"DqTc0xVO7j3vmZ1J_L-ayFOx2AA6wXGNZ9Kr6x23Y-THKWnAVSC5nw=="
      },
      "status":422,
      "text":"{\"error\":\"UNSATISFIED_RANGE\",\"data\":{\"name\":\"@angular/cdk\",\"range\":\"12.2.7\"}}"
   }
}
```

Example: https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fcheckbox-overview-example.ts
Browser: Chrome

Steps followed: 
Tried with another browser - Firefox, but still the same problem. The examples are opening fine from previous Angular Material website version.

Example: 
https://v11.material.angular.io/components/checkbox/overview
https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fcheckbox-overview-example.ts

What I noticed that the old version of Angular Material website (https://v11.material.angular.io/components/checkbox/overview ) opens the same link: https://run.stackblitz.com/api/angular/v1?file=src%2Fapp%2Fcheckbox-overview-example.ts as the newest Angular version (12.2.7) in a new tab, then it redirects successfully to: https://stackblitz.com/angular/gobxbernjrb?file=src%2Fapp%2Fcheckbox-overview-example.ts, whereas the new version does not redirect and displays the json containing an error.

Might be a duplicate to issue: https://github.com/angular/material.angular.io/issues/1049

**Comment by Splaktar** [comment]
It looks like https://github.com/angular/material.angular.io/commit/f41506ac505206763b384808e196a6bb2459d1d5 hasn't been cherry-picked into the `12.x` branch yet.

**Comment by Splaktar** [comment]
Fixed in PR https://github.com/angular/material.angular.io/pull/1077.
