### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by jbergdev** [angular/material.angular.io#1148]
Website is down on desktop and mobile. Console error:

> Failed to load resource: the server responded with a status of 404 ()

I am running Chrome Version 102.0.5005.61 (Official Build) (x86_64

**Comment by nejat-njonjo** [comment]
Yes. Am getting the same error on chrome.

GET https://material.angular.io/polyfills.ed0d8bd5f94ef931.js net::ERR_ABORTED 404
GET https://material.angular.io/main.ca385c283b9e57f2.js net::ERR_ABORTED 404

**Comment by jbergdev** [comment]
The website is now working for me.
