### ISSUE TITLE
Opening certain components in a new tab results in a 404.

### ISSUE THREAD

**Issue by JackMBurch** [angular/material.angular.io#1149]
Opening certain components in a new tab from https://material.angular.io/components/categories/overview results in a 404 and doesn't redirect to the /overview page. For example, Autocomplete doesn't work, but Badge does. This also seems to affect the categories page when trying to link to it.

**Comment by amysorto** [comment]
Autocomplete works when I tried, couldn't see a 404 page so I will close this issue.

**Comment by JackMBurch** [comment]
Yup, seems like this works as expected now.
