### ISSUE TITLE
material.angular.io inconsistently inaccessible

### ISSUE THREAD

**Issue by bethge** [angular/material.angular.io#1150]
Visiting material.angular.io returns a 200 with a blank page. The console shows that main scripts failed to load.

This is inconsistently reproducible across locations and started ~1hour ago for me:

Local laptop as well as local workstation (in UK) - the main page https://material.angular.io/  as well as various sub pages return blank with a 200 response code across all 3 tested browsers:
- Stable Chrome
- Canary Chrome
- Safari

Yet, accessing https://material.angular.io/cdk/table/api loads fully and from there clicking on home routes to https://material.angular.io/ which then does load. I assume because it's a SPA.

On a virtual machine in Netherlands:
- Directly loading https://material.angular.io/ works fine.

Locally cleared site data, service workers etc. multiple times to no avail.

```
[Error] Failed to load resource: the server responded with a status of 404 () (polyfills.ed0d8bd5f94ef931.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (main.ca385c283b9e57f2.js, line 0)
```

**Comment by tominyorks** [comment]
Exactly the same behaviour for me (also UK based) - I've tried Chrome, Firefox and Edge Chromium with the same results in all three

**Comment by jbergdev** [comment]
This was happening to me yesterday, but the behavior eventually stopped for me. Has been stable ever since.
