### ISSUE TITLE
next.material.angular.io site stuck at v15.0.0-next.0 and examples broken

### ISSUE THREAD

**Issue by vdumbrav** [angular/material.angular.io#1168]
I found some issues on next.material.angular.io  
- error in console `Could not find example: snack-bar-annotated-component-example
set example @ 5469.0fac45563d5b409b.js:1
`
- these pages with examples are broken 
https://next.material.angular.io/components/slider/examples
https://next.material.angular.io/components/datepicker/examples
- elements from sidebar is not center
![image](https://user-images.githubusercontent.com/24795169/187461668-df84be01-a98a-47af-88c4-81ff37a2c67e.png)

**Comment by Totati** [comment]
Seems to be fixed.
