### ISSUE TITLE
Swiping slider doesn't work

### ISSUE THREAD

**Issue by mmalerba** [angular/material.angular.io#120]
As mentioned in https://github.com/angular/material2/issues/3394 the swipe gesture doesn't seem to be working on md-slider on the docs site (https://material.angular.io/components/component/slider) in firefox. It does however work in the plunker link on the same example, so seems like something on the docs site is interfering.

**Comment by mmalerba** [comment]
This is caused by angular not recognizing that HammerJS is loaded (following warning can be observed in the console: `Could not find HammerJS. Certain Angular Material components may not work correctly.`)

@jelbourn This can be fixed by removing `async` on the HammerJS script, though maybe we should try to detect when HammerJS loads late and enable swipe support?

**Comment by jelbourn** [comment]
@mmalerba The latter would be nice. @crisbeto any thoughts?

**Comment by crisbeto** [comment]
It makes sense to check for Hammer when we try to bind something, instead of the constructor. I'll play around with it and put in a PR.
