### ISSUE TITLE
version-picker.ts has a bug

### ISSUE THREAD

**Issue by shayan-ghzl** [angular/material.angular.io#1233]
hi
in this file (version-picker.ts), 
**onVersionChanged** handler has an if statement in which its condition is always true

!version.url.startsWith(window.location.href)
                               ⇩
!"https://material.angular.io".startsWith("https://material.angular.io/")    =>    its always true due to a **forward slash /**

**Comment by amysorto** [comment]
Thanks! Closing since fixed in #1234
