### ISSUE TITLE
Add links for additional help/support resources

### ISSUE THREAD

**Issue by andrewseguin** [angular/material.angular.io#133]
The docs site could use a page helping users find outlets to the community and where they can ask questions or provide support for others looking for help.

- Google Groups
- StackOverflow
- Gitter

**Comment by jelbourn** [comment]
I really like the design from https://developers.google.com/web

![image](https://cloud.githubusercontent.com/assets/838736/24833010/c23084c2-1c7a-11e7-8dee-b78dcf31b5a3.png)

**Comment by kian23kpt** [comment]
@jelbourn I add links for additional help/support resources like google developers site, I hope you like it
![Screenshot (2)](https://user-images.githubusercontent.com/48172978/106361891-17e17480-6335-11eb-8400-9ada4db4aadd.png)

**Comment by Splaktar** [comment]
@kian23kpt it would be helpful to add screenshots of desktop and mobile to the first post in your PR.
