### ISSUE TITLE
The selector did not match any elements

### ISSUE THREAD

**Issue by kronetorres** [angular/material.angular.io#137]
The [Dialog Component ](https://material.angular.io/components/component/dialog) in the plunker Demo throws exeption: "The selector "dialog-overview-example-dialog" did not match any elements".

**Comment by kronetorres** [comment]
Fix:
change 

` bootstrap: [DialogResultExample, DialogResultExampleDialog],`

for
```
bootstrap: [DialogResultExample],
entryComponents: [DialogResultExampleDialog],
```

**Comment by rbaumi** [comment]
I suggest you change the plunker and docs :)
