### ISSUE TITLE
Dialog example should include code from dialog-result-example-dialog.html

### ISSUE THREAD

**Issue by jrood** [angular/material.angular.io#149]
The overview for the Dialog talks about using elements such as `<md-dialog-content>` and `<md-dialog-actions>`.  However, no examples of actual code using these elements is visible, because that code would be in the  dialog-result-example-dialog.html file (referenced in the .ts files in both the overview and the example), but the actual content of that html file is not visible anywhere.

**Comment by jrood** [comment]
Also, it's not clear whether DialogResultExampleDialog needs to be a component module or how it might need to be referenced in the app.module.ts. (I'm willing to make a second issue for this if anyone thinks that is necessary).

**Comment by jelbourn** [comment]
Tracking via #165
