### ISSUE TITLE
Duplicate properties in API docs

### ISSUE THREAD

**Issue by KyleMcNutt** [angular/material.angular.io#164]
![image](https://user-images.githubusercontent.com/3861611/26857422-46d65b92-4adf-11e7-875d-0fecaa2d2f0f.png)

This is an example taken from the API references tab of the Select Component.

**Comment by jelbourn** [comment]
Will be fixed on next push

**Comment by Splaktar** [comment]
I can confirm that this is fixed in production. This issue should be able to be closed now.
