### ISSUE TITLE
Add table-of-contents for jump navigation on docs

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#167]
Similar to the right-hand-side of https://developers.google.com/web/fundamentals/getting-started/principles/

**Comment by amcdnl** [comment]
See: https://github.com/angular/material.angular.io/pull/230 and https://github.com/angular/material2/pull/6040

**Comment by amysorto** [comment]
Closing this issue since a TOC for a page been a part of the docs site for a while now
