### ISSUE TITLE
Support multiple versions of documentation

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#168]

**Comment by TheRedD0t** [comment]
Any progress? Now that beta versions are also released, it makes even more sense to have a possibility to choose between the different versions.

**Comment by jelbourn** [comment]
Done in v6.

**Comment by chrste90** [comment]
@jelbourn Do you also plan to add a next version to the docs like on `angular.io`?

**Comment by jelbourn** [comment]
At some point, but not in the immediate future
