### ISSUE TITLE
Create fetch-local-assets script

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#172]
Would work the same as `fetch-assets.sh`, but instead of fetching published assets from the material2-docs-content repo, would build and copy assets from a local material2 repo.

**Comment by amcdnl** [comment]
@jelbourn - 

Rather than cloning the `https://github.com/angular/material2-docs-content` path, what do you think about looking at the cousin directory `material2`?

So something like:`cp -r ../material2/dist/release/material-examples ${tmpAssetClonePath}`?

**Comment by jelbourn** [comment]
Yeah, my thinking had been 
1. If argument given, use that as the path
2. Try `~/material2`
3. Try `../material2`
4. Try environment variable `MATERIAL2_LOCAL`
5. Weep

**Comment by amcdnl** [comment]
First cut of the script:

```
#!/bin/bash

# Base Source Path
if [ -d ~/material2 ] ; then
  echo "- Using path ~/material2"
  baseSrcPath=~/material2
elif [ -d ../material2 ] ; then
  echo "- Using path ../material2"
  baseSrcPath=../material2
elif [ -d ${MATERIAL2_LOCAL} ] ; then
  echo "- Using MATERIAL2_LOCAL env variable"
  baseSrcPath = ${MATERIAL2_LOCAL}
fi

if [ ! -d ${baseSrcPath}/dist/docs ] ; then
  echo "!! Missing /dist/docs... Did you run 'gulp docs'??"
  exit
fi

if [ ! -d ${baseSrcPath}/dist/releases/material-examples ] ; then
  echo "!! Missing /dist/releases/material-examples ... Did you run 'gulp material-examples:build-release'??"
  exit
fi

# Base Target Path
baseTargetPath=./src/assets

# Copy Packages
echo "- Copying Package Files to node_modules"
mkdir -p ./node_modules/@angular/material-examples
cp -r ${baseSrcPath}/dist/releases/material-examples ./node_modules/@angular/

# Copy Examples
echo "- Copying Examples"
cp -r ${baseSrcPath}/dist/docs/examples ${baseTargetPath}

# Copy API Files
echo "- Copying API"
cp -r ${baseSrcPath}/dist/docs/api ${baseTargetPath}/documents

# Copy Guide files
echo "- Copying Guides"
mkdir -p ./src/assets/documents/guides
cp ${baseSrcPath}/dist/docs/markdown/*.html ${baseTargetPath}/documents/guides

# Copy Overview
echo "- Copying Overview"
mkdir -p ./src/assets/documents/overview
cp ${baseSrcPath}/dist/docs/markdown/*/*.html ${baseTargetPath}/documents/overview
```

The previous script had a provision for copying plunker files. I am unable to determine where those files were coming from. The files in `material2/dist/docs/plunker` does not seem to match up to the files in the repo of `material.angular.io`.

@jelbourn - Let me know how this looks and I'll PR it up.

**Comment by jelbourn** [comment]
Looks good at a high level. Two things I'd change:
* Instead of checking for `dist/docs`, just build them. If someone is running this script it means they've changed something and they want to copy it over, so might as well build them all in one command.
* No need to echo the individual copy operations, they should be quite instantaneous.

**Comment by amcdnl** [comment]
@jelbourn - Should it build them everytime or just when they are not present?

**Comment by jelbourn** [comment]
I was thinking every time since why else would you run it unless you changed something and want an update
