### ISSUE TITLE
Broken md-sidenav in docs

### ISSUE THREAD

**Issue by bradyshutt** [angular/material.angular.io#178]
On both the [material.angular.io site](https://material.angular.io/components/component/sidenav) and the [firebase site](https://material2-docs-dev.firebaseapp.com/components/component/sidenav), the page showcasing the sidenav component is broken. On page load, the sidenav is open (and displayed a little funky), and clicking the `Open sidenav` button throws this error:
`` ERROR TypeError: pe._33(...).open is not a function ``

See: [https://prnt.sc/fib9i6](https://prnt.sc/fib9i6)

**Comment by jelbourn** [comment]
The example is fixed already on master and it will be published soon.

**Comment by willshowell** [comment]
Can be closed now!
