### ISSUE TITLE
Design Search

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#19]
Not a top priority, but we will need to have an in-site search eventually.  My current thinking is to add it to the top nav. Probably includes an autocomplete. 

Also need to think about how to to show the results.

**Comment by jelbourn** [comment]
I like the search on https://developers.google.com/analytics/

**Comment by amitafr** [comment]
Note: Remove Components tab and condense Angular Material logo on Tablet and Mobile

**Comment by amitafr** [comment]
![search](https://cloud.githubusercontent.com/assets/10601477/20940160/c2593ff0-bbbf-11e6-95c3-ca5072330f0a.jpg)
