### ISSUE TITLE
Update CLI version to latest

### ISSUE THREAD

**Issue by lacolaco** [angular/material.angular.io#195]
Update `@angular/cli` version to the latest to make easy development/contribution.

- rename `angular-cli.json` to `.angular-cli.json`
- migrate `.angular-cli.json` configurations
- add/remove some files

migrating guide: https://github.com/angular/angular-cli/wiki/stories-1.0-update

**Comment by Splaktar** [comment]
This would be helpful! Thank you for the PR.

Of course the CLI is on 1.2.0 now :)

**Comment by Splaktar** [comment]
With version 9, we've updated the project to better align with default Angular CLI projects in many ways.

PR https://github.com/angular/material.angular.io/pull/696 updates to the latest v9 RC of the CLI as well.
