### ISSUE TITLE
Proposal: max-width on app-component-viewer

### ISSUE THREAD

**Issue by willshowell** [angular/material.angular.io#197]
I haven't fully investigated if this would be appropriate everywhere, but when reading the component overviews on a full screen (> 1500px), lots of paragraphs get stretched out to one line and the legibility and reading comfort is lost.

I suggest setting a max-width of about 800-900 px and centering it in its parent.

### Before
![screen shot 2017-06-22 at 4 57 57 pm](https://user-images.githubusercontent.com/6475576/27455644-053bba76-576c-11e7-8dbd-2603b2b94408.png)

### After 
![screen shot 2017-06-22 at 4 57 40 pm](https://user-images.githubusercontent.com/6475576/27455652-0abcd840-576c-11e7-9bd7-70b0f07a9795.png)

**Comment by jelbourn** [comment]
It's so obvious now that you've pointed it out. I'd set the max-width to 940px (copying the Android docs). 

Feel free to send a PR!
