### ISSUE TITLE
Design "Live Example" component

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#2]
This should cover the features that are [available in the material docs site](https://material.angularjs.org/latest/demo/autocomplete):
* Live example
* Can expand source in-page
* Can link out to Plunker

It would also be good to add an LTR/RTL toggle for the examples as well, but that may come later in the implementation.

![image](https://cloud.githubusercontent.com/assets/838736/20164059/635aa5f2-a6b6-11e6-94da-b4131ef61327.png)

**Comment by amitafr** [comment]
![material internal page info tip](https://cloud.githubusercontent.com/assets/10601477/20467739/a43eb1f0-af5b-11e6-9a2e-467a0469afd1.jpg)

**Comment by amitafr** [comment]
![overview](https://cloud.githubusercontent.com/assets/10601477/20942719/adeab2aa-bbca-11e6-8233-25156b85aaaa.jpg)

**Comment by amitafr** [comment]
Live Example Styles:
**Overview**
- Simple and Basic Functionality of component 
- Use site's primary and accent colour palette 
- If necessary add titles, descriptions and/or labels to examples 

**Examples**
- Showcase the component’s functionality
- Next steps to explore 
- Advanced features for the component 
- Alternative uses for component if applicable 
- Use site's primary and accent colour palette
- If necessary add titles, descriptions and/or labels to examples 

Code Example:

![code](https://cloud.githubusercontent.com/assets/10601477/20976080/65b88f70-bc6f-11e6-8068-136b4ab39a15.png)
