### ISSUE TITLE
Implement theme switcher

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#20]
We're going to shamelessly steal the picker from https://fonts.google.com/

This is lower priority than the main docs content

**Comment by jelbourn** [comment]
Oh, also we should make it so that the different themes are separate files that we lazily load when the theme changes (instead of loading them all at once).

**Comment by Splaktar** [comment]
Theme switching seems to be implemented now:
https://github.com/angular/material.angular.io/pull/136
https://github.com/angular/material.angular.io/pull/188

This can probably be closed?
