### ISSUE TITLE
Error when navigate to unknown component

### ISSUE THREAD

**Issue by rafaelss95** [angular/material.angular.io#215]
**Steps to reproduce:**

1 - When you navigate to something like:
https://material.angular.io/components/anything

2 - You get the following error:

> TypeError: Cannot read property 'unsubscribe' of undefined

Well, the issue itself is in the website, however the error is coming from `material2` repo (specifically in [this line](https://github.com/angular/material2/blob/1b351cdb868b7c31c8d77b4e91d8518ce149f407/src/lib/tabs/tab-nav-bar/tab-nav-bar.ts#L89)).

**Comment by rafaelss95** [comment]
@jelbourn  The fix would be simple as wrap the `unsubscribe` inside `if` statement? Or is there something else?

**Comment by jelbourn** [comment]
Yeah, just needs to check if the subscription exists

**Comment by willshowell** [comment]
Looks like this can be closed

**Comment by rafaelss95** [comment]
@willshowell done :)
