### ISSUE TITLE
Support deep linking in api docs

### ISSUE THREAD

**Issue by willshowell** [angular/material.angular.io#219]
E.g. `/components/tooltip/api#disabled` (or `#property-disabled`)

![screen shot 2017-07-11 at 9 18 13 am](https://user-images.githubusercontent.com/6475576/28074229-0cabbce8-6626-11e7-9b23-cfbebb003673.png)

**Comment by willshowell** [comment]
@amcdnl is this something that could easily leverage your TOC work?

**Comment by amcdnl** [comment]
@willshowell - The TOC work addresses headers only. It would take a bit more work to handle every nook like this.

**Comment by amysorto** [comment]
Closing since this is supported (lots of headers have a link button on hover next to it you can copy for the specific text)
