### ISSUE TITLE
Accent color in 'pink-bluegrey' theme

### ISSUE THREAD

**Issue by rafaelss95** [angular/material.angular.io#222]
The theme `pink-bluegrey` makes the accent color hard to see (it seems like the default):

![](https://i.stack.imgur.com/U5UCi.png)
![](https://i.stack.imgur.com/VXvPB.png)

The same happens to radio-buttons, checkboxes.

**Comment by dhrn** [comment]
@amcdnl i am planning to work on this issue.

**Comment by dhrn** [comment]
$accent:  mat-palette($mat-green, A200, A100, A400);
This is the accent color. what i have to do here?

**Comment by beeman** [comment]
Agreed that this is unclear. I suggest we change the `pink-bluegray` to either `ping-amber` or `pink-lightgreen`.

### Amber Chips

![image](https://user-images.githubusercontent.com/36491/50911065-3c004f00-1416-11e9-8185-0cad904e4799.png)

### Amber Slide-toggle
![image](https://user-images.githubusercontent.com/36491/50911148-6520df80-1416-11e9-88d8-4f24404c4a08.png)

### Amber Badges
![image](https://user-images.githubusercontent.com/36491/50911220-8da8d980-1416-11e9-8855-8327d54dfab7.png)

### Amber Buttons
![image](https://user-images.githubusercontent.com/36491/50911529-35260c00-1417-11e9-87d2-832ea9cc4960.png)

### Light Green Chips
![image](https://user-images.githubusercontent.com/36491/50911686-8a621d80-1417-11e9-89c0-ebbd82d84935.png)

### Light Green Slide-toggle
![image](https://user-images.githubusercontent.com/36491/50911803-c8f7d800-1417-11e9-8565-b4b21ae92bbb.png)

### Light Green Badges
![image](https://user-images.githubusercontent.com/36491/50911844-d90fb780-1417-11e9-9acf-ce50362327eb.png)

### Light Green Buttons
![image](https://user-images.githubusercontent.com/36491/50911869-e7f66a00-1417-11e9-8497-4065562c9687.png)
