### ISSUE TITLE
md-autocomplete - problem characters

### ISSUE THREAD

**Issue by christianirack** [angular/material.angular.io#226]
In the tutorial page:

The console displays an error when you try to insert any of the following characters... 

filter(val: string): string[] {
    return this.options.filter(option => new RegExp(`^${val}`, 'gi').test(option));
  }

(, [, ...

**Comment by christianirack** [comment]
A solution may be:

 val = val.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&");
 return this.options.filter(option => new RegExp(`^${val}`, 'gi').test(option));

**Comment by willshowell** [comment]
Luckily there's a PR at https://github.com/angular/material2/pull/5787 to replace the autocomplete code snippets with live examples. One of the changes is to use `indexOf(val) === 0)` instead of the regex

**Comment by josephperrott** [comment]
Resolved via https://github.com/angular/material2/pull/5787
