### ISSUE TITLE
ERRORS ERRORS ERRORS

### ISSUE THREAD

**Issue by chrisformula** [angular/material.angular.io#231]
This project was working yesterday...... Why does this happen?

ERROR in /node_modules/@angular/material/typings/core/bidi/index.d.ts (8,99): Cannot find module '@angular/cdk/bidi'.

ERROR in /node_modules/@angular/material/typings/core/portal/portal.d.ts (8,85): Cannot find module '@angular/cdk/portal'.

ERROR in //node_modules/@angular/material/typings/core/portal/portal-directives.d.ts (8,76): Cannot find module '@angular/cdk/portal'.

ERROR in /node_modules/@angular/material/typings/core/portal/dom-portal-host.d.ts (8,31): Cannot find module '@angular/cdk/portal'.

ERROR in /node_modules/@angular/material/typings/core/platform/platform.d.ts (8,26): Cannot find module '@angular/cdk/platform'.

ERROR in /node_modules/@angular/material/typings/core/platform/features.d.ts (8,40): Cannot find module '@angular/cdk/platform'.

ERROR in /node_modules/@angular/material/typings/core/platform/index.d.ts (8,32): Cannot find module '@angular/cdk/platform'.

ERROR in /node_modules/@angular/material/typings/core/a11y/live-announcer.d.ts (8,139): Cannot find module '@angular/cdk/a11y'.

ERROR in /node_modules/@angular/material/typings/core/a11y/focus-trap.d.ts (8,95): Cannot find module '@angular/cdk/a11y'.

ERROR in /node_modules/@angular/material/typings/core/a11y/interactivity-checker.d.ts (8,38): Cannot find module '@angular/cdk/a11y'.

ERROR in /node_modules/@angular/material/typings/core/a11y/fake-mousedown.d.ts (8,49): Cannot find module '@angular/cdk/a11y'.

ERROR in /node_modules/@angular/material/typings/core/a11y/index.d.ts (8,28): Cannot find module '@angular/cdk/a11y'.

ERROR in /node_modules/@angular/material/typings/core/keyboard/keycodes.d.ts (8,140): Cannot find module '@angular/cdk/keyboard'.

ERROR in /node_modules/@angular/material/typings/core/core.d.ts (1,61): Cannot find module '@angular/cdk/coercion'.

ERROR in /node_modules/@angular/material/typings/core/core.d.ts (2,54): Cannot find module '@angular/cdk/observe-content'.

ERROR in /node_modules/@angular/material/typings/core/a11y/list-key-manager.d.ts (8,44): Cannot find module '@angular/cdk/a11y'.

ERROR in /node_modules/@angular/material/typings/chips/chip-list.d.ts (11,32): Cannot find module '@angular/cdk/bidi'.

ERROR in /node_modules/@angular/material/typings/sort/sort-header.d.ts (11,30): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material/typings/table/cell.d.ts (9,54): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material/typings/table/table.d.ts (1,26): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material/typings/table/row.d.ts (1,38): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material-examples/typings/cdk-table-basic/cdk-table-basic-example.d.ts (1,28): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material-examples/typings/table-basic/table-basic-example.d.ts (1,28): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material-examples/typings/table-http/table-http-example.d.ts (2,28): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material-examples/typings/table-filtering/table-filtering-example.d.ts (2,28): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material-examples/typings/table-overview/table-overview-example.d.ts (2,28): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material-examples/typings/table-pagination/table-pagination-example.d.ts (1,28): Cannot find module '@angular/cdk/table'.

ERROR in /node_modules/@angular/material-examples/typings/table-sorting/table-sorting-example.d.ts (1,28): Cannot find module '@angular/cdk/table'.

ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/cdk/table relative to /node_modules/@angular/material-examples/typings/index.d.ts., resolving symbol ɵct in/node_modules/@angular/material-examples/typings/index.d.ts, resolving symbol ɵct in /node_modules/@angular/material-examples/typings/index.d.ts

ERROR in ./~/@angular/material-examples/@angular/material-examples.es5.js
Module not found: Error: Can't resolve '@angular/cdk/table' in '/node_modules/@angular/material-examples/@angular'
 @ ./~/@angular/material-examples/@angular/material-examples.es5.js 12:0-64
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/table' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 31:0-160
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/observe-content' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 10:0-84
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/bidi' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 12:0-68
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/platform' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 14:0-89
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/rxjs' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 19:0-159
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/keyboard' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 20:0-163
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/coercion' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 21:0-84
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/portal' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 22:0-169
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/@angular/material/@angular/material.es5.js
Module not found: Error: Can't resolve '@angular/cdk/a11y' in '/node_modules/@angular/material/@angular'
 @ ./~/@angular/material/@angular/material.es5.js 23:0-267
 @ ./src/app/app-module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

Any help or direction will be appreciated.

**Comment by Chan4077** [comment]
Have you tried deleting the `node_modules` folder then running `npm install` again?

**Comment by ericdemo07** [comment]
Same issue here
project was working fine yesterday and now am getting same error logs

Tried deleting node_module
issue still continues

**Comment by factedu** [comment]
npm install --save @angular/material @angular/cdk

solved my problem

**Comment by ricsairis** [comment]
I got the same error as @chrisformula and did as @factedu said and it worked for me.

**Comment by ericdemo07** [comment]
Added

    '@angular/cdk': 'npm:@angular/cdk/bundles/cdk.umd.js',
      '@angular/cdk/a11y': 'npm:@angular/cdk/bundles/cdk-a11y.umd.js',
      '@angular/cdk/bidi': 'npm:@angular/cdk/bundles/cdk-bidi.umd.js',
      '@angular/cdk/coercion': 'npm:@angular/cdk/bundles/cdk-coercion.umd.js',
      '@angular/cdk/collections': 'npm:@angular/cdk/bundles/cdk-collections.umd.js',
      '@angular/cdk/keycodes': 'npm:@angular/cdk/bundles/cdk-keycodes.umd.js',
      '@angular/cdk/observers': 'npm:@angular/cdk/bundles/cdk-observers.umd.js',
      '@angular/cdk/overlay': 'npm:@angular/cdk/bundles/cdk-overlay.umd.js',
      '@angular/cdk/platform': 'npm:@angular/cdk/bundles/cdk-platform.umd.js',
      '@angular/cdk/portal': 'npm:@angular/cdk/bundles/cdk-portal.umd.js',
      '@angular/cdk/rxjs': 'npm:@angular/cdk/bundles/cdk-rxjs.umd.js',
      '@angular/cdk/table': 'npm:@angular/cdk/bundles/cdk-table.umd.js',
      '@angular/cdk/scrolling': 'npm:@angular/cdk/bundles/cdk-scrolling.umd.js',

into system.config

and things went fine

**Comment by Deepakchawla** [comment]
Thanks a lot...
I got the same error as @chrisformula and did as @factedu said and it worked for me.

**Comment by shibut12** [comment]
Thank you so much, I got the same error as @chrisformula and did what @factedu suggested. I had ng-serve running while installing angular/cdk, and in the beginning, it looked like installing cdk didn't fix the issue. I stopped ng-serve and started again, I'm no longer getting this error.

**Comment by brahimkra** [comment]
I have this error when i'm using angular/material and can't solve it :
ERROR in /home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/material/list/typings/list.d.ts (61,22): Class 'MatListItem' incorrectly implements interface 'CanDisableRipple'.
  Property 'disableRipple' is missing in type 'MatListItem'.
ERROR in /home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/material/core/typings/common-behaviors/common-module.d.ts (8,10): Module '"/home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
ERROR in /home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/material/core/typings/compatibility/compatibility.d.ts (8,10): Module '"/home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
ERROR in /home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/material/core/typings/datetime/date-adapter.d.ts (8,10): Module '"/home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
ERROR in /home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/material/core/typings/datetime/date-formats.d.ts (8,10): Module '"/home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
ERROR in /home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/material/core/typings/line/line.d.ts (8,10): Module '"/home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
ERROR in /home/brahim/WebstormProjects/firebase-authentification/node_modules/@angular/material/core/typings/option/optgroup.d.ts (9,22): Class 'MatOptgroup' incorrectly implements interface 'CanDisable'.
  Property 'disabled' is missing in type 'MatOptgroup'.

**Comment by jelbourn** [comment]
Closing this as obsolete.

**Comment by actiontom** [comment]
Hi,
So I've downloaded an opos and I'm getting the same issue when trying to build the project. What was the resolution? I've tried all of the above with no luck.

**Comment by rahulgupta1210** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

E:\grabit>ng serve
** NG Live Development Server is listening on localhost:4200, open your browser
on http://localhost:4200/ **
 10% building modules 0/1 modules 1 active ...ttp://0.0.0.0:0 E:\grabit\src\main
 10% building modules 2/3 modules 1 active ...trap.min.css E:\grabit\src\styles.
 10% building modules 3/4 modules 1 active ...rver\client\index.js?http://0.0.0.
 10% building modules 4/5 modules 1 active ...ck\src\index.js!E:\grabit\src\main
 10% building modules 4/6 modules 2 active ...c\index.js!E:\grabit\src\polyfills
 10% building modules 5/6 modules 1 active ...c\index.js!E:\grabit\src\polyfills
 10% building modules 6/7 modules 1 active ...s\webpack-dev-server\client\socket
 10% building modules 6/9 modules 3 active ...\webpack-dev-server\client\overlay
 10% building modules 6/10 modules 4 active ...js??embedded!E:\grabit\src\styles
 10% building modules 7/10 modules 3 active ...\webpack-dev-server\client\overla
 10% building modules 7/11 modules 4 active ...\bootstrap\dist\css\bootstrap.min
 10% building modules 8/11 modules 3 active ...\webpack-dev-server\client\overla
 10% building modules 8/12 modules 4 active ...js??embedded!E:\grabit\src\styles
 10% building modules 8/13 modules 5 active ...\bootstrap\dist\css\bootstrap.min
 10% building modules 8/14 modules 6 active ...\webpack\hot nonrecursive /^\.\/l
 11% building modules 9/14 modules 5 active ...\webpack\hot nonrecursive /^\.\/l
 11% building modules 10/14 modules 4 active ...\webpack\hot nonrecursive /^\.\/
 11% building modules 11/14 modules 3 active ...\webpack\hot nonrecursive /^\.\/
 11% building modules 12/14 modules 2 active ...\bootstrap\dist\css\bootstrap.mi
 11% building modules 12/15 modules 3 active ...modules\style-loader\lib\addStyl
 11% building modules 13/15 modules 2 active ...modules\style-loader\lib\addStyl
 11% building modules 14/15 modules 1 active ...modules\style-loader\lib\addStyl
 11% building modules 14/16 modules 2 active ...t\node_modules\webpack\hot\emitt
 11% building modules 15/16 modules 1 active ...t\node_modules\webpack\hot\emitt
 11% building modules 15/17 modules 2 active ...rabit\node_modules\webpack\hot\l
 11% building modules 15/19 modules 4 active ...ser\node_modules\punycode\punyco
 11% building modules 15/20 modules 5 active ...node_modules\querystring-es3\ind
 11% building modules 16/20 modules 4 active ...node_modules\querystring-es3\ind
 12% building modules 17/20 modules 3 active ...node_modules\querystring-es3\ind
 12% building modules 18/20 modules 2 active ...node_modules\querystring-es3\ind
 12% building modules 19/20 modules 1 active ...node_modules\querystring-es3\ind
 12% building modules 20/21 modules 1 active ...node_modules\style-loader\lib\ur
 12% building modules 20/22 modules 2 active ...abit\node_modules\strip-ansi\ind
 12% building modules 20/23 modules 3 active ...node_modules\loglevel\lib\loglev
 12% building modules 20/24 modules 4 active ...ode_modules\webpack\buildin\modu
 12% building modules 20/25 modules 5 active ...ode_modules\webpack\buildin\glob
 12% building modules 20/26 modules 6 active E:\grabit\node_modules\events\event
 12% building modules 21/26 modules 5 active E:\grabit\node_modules\events\event
 12% building modules 22/26 modules 4 active E:\grabit\node_modules\events\event
 12% building modules 22/27 modules 5 active ...ode_modules\querystring-es3\deco
 12% building modules 22/28 modules 6 active ...ode_modules\querystring-es3\enco
 12% building modules 23/28 modules 5 active ...ode_modules\querystring-es3\enco
 12% building modules 24/28 modules 4 active ...ode_modules\querystring-es3\enco
 13% building modules 25/28 modules 3 active ...ode_modules\querystring-es3\enco
 13% building modules 26/28 modules 2 active ...ode_modules\querystring-es3\enco
 13% building modules 26/29 modules 3 active ...rabit\node_modules\ansi-html\ind
 13% building modules 26/30 modules 4 active ..._modules\sockjs-client\dist\sock
 13% building modules 27/30 modules 3 active ..._modules\sockjs-client\dist\sock
 13% building modules 28/30 modules 2 active ..._modules\sockjs-client\dist\sock
 13% building modules 29/30 modules 1 active ..._modules\sockjs-client\dist\sock
 13% building modules 29/31 modules 2 active ...t\node_modules\html-entities\ind
 13% building modules 30/31 modules 1 active ...t\node_modules\html-entities\ind
 13% building modules 31/32 modules 1 active ...les\html-entities\lib\xml-entiti
 13% building modules 31/33 modules 2 active ...s\html-entities\lib\html4-entiti
 13% building modules 31/34 modules 3 active ...s\html-entities\lib\html5-entiti
 13% building modules 32/34 modules 2 active ...s\html-entities\lib\html5-entiti
 13% building modules 33/34 modules 1 active ...s\html-entities\lib\html5-entiti
 14% building modules 34/35 modules 1 active ...abit\node_modules\ansi-regex\ind
Date: 2018-04-22T11:59:00.007Z
Hash: 88a7dc1e36f766b86049
Time: 8615ms
chunk {inline} inline.bundle.js (inline) 3.85 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 2.91 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 bytes [initial] [rendered]

chunk {scripts} scripts.bundle.js (scripts) 158 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 424 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 852 kB [initial] [rendered]

ERROR in node_modules/@angular/material/autocomplete/typings/autocomplete-trigge
r.d.ts(8,32): error TS2307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/autocomplete/typings/autocomplete-trigger.d.ts(9,
41): error TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/autocomplete/typings/autocomplete.d.ts(10,44): er
ror TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts(8,30): e
rror TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/button-toggle/typings/button-toggle.d.ts(9,43): e
rror TS2307: Cannot find module '@angular/cdk/collections'.
node_modules/@angular/material/button/typings/button.d.ts(8,30): error TS2307: C
annot find module '@angular/cdk/a11y'.
node_modules/@angular/material/button/typings/button.d.ts(9,26): error TS2307: C
annot find module '@angular/cdk/platform'.
node_modules/@angular/material/checkbox/typings/checkbox.d.ts(8,30): error TS230
7: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/chips/typings/chip-list.d.ts(8,33): error TS2307:
 Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/chips/typings/chip-list.d.ts(9,32): error TS2307:
 Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/chips/typings/chip-list.d.ts(10,32): error TS2307
: Cannot find module '@angular/cdk/collections'.
node_modules/@angular/material/chips/typings/chip.d.ts(8,33): error TS2307: Cann
ot find module '@angular/cdk/a11y'.
node_modules/@angular/material/core/typings/ripple/ripple-renderer.d.ts(9,26): e
rror TS2307: Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/core/typings/ripple/ripple.d.ts(8,26): error TS23
07: Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/datepicker/typings/calendar.d.ts(7,32): error TS2
307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/datepicker/typings/datepicker.d.ts(8,32): error T
S2307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/datepicker/typings/datepicker.d.ts(9,67): error T
S2307: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/dialog/typings/dialog-config.d.ts(9,27): error TS
2307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/dialog/typings/dialog-config.d.ts(10,32): error T
S2307: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/dialog/typings/dialog-container.d.ts(10,84): erro
r TS2307: Cannot find module '@angular/cdk/portal'.
node_modules/@angular/material/dialog/typings/dialog-container.d.ts(11,34): erro
r TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/dialog/typings/dialog-ref.d.ts(8,28): error TS230
7: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/dialog/typings/dialog.d.ts(1,59): error TS2307: C
annot find module '@angular/cdk/overlay'.
node_modules/@angular/material/dialog/typings/dialog.d.ts(2,31): error TS2307: C
annot find module '@angular/cdk/portal'.
node_modules/@angular/material/expansion/typings/accordion.d.ts(1,30): error TS2
307: Cannot find module '@angular/cdk/accordion'.
node_modules/@angular/material/expansion/typings/expansion-panel-header.d.ts(8,3
0): error TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/expansion/typings/expansion-panel.d.ts(10,34): er
ror TS2307: Cannot find module '@angular/cdk/accordion'.
node_modules/@angular/material/expansion/typings/expansion-panel.d.ts(11,43): er
ror TS2307: Cannot find module '@angular/cdk/collections'.
node_modules/@angular/material/expansion/typings/expansion-panel.d.ts(12,32): er
ror TS2307: Cannot find module '@angular/cdk/portal'.
node_modules/@angular/material/grid-list/typings/grid-list.d.ts(10,32): error TS
2307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/input/typings/autosize.d.ts(9,26): error TS2307:
Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/input/typings/input.d.ts(1,26): error TS2307: Can
not find module '@angular/cdk/platform'.
node_modules/@angular/material/list/typings/selection-list.d.ts(8,50): error TS2
307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/list/typings/selection-list.d.ts(9,32): error TS2
307: Cannot find module '@angular/cdk/collections'.
node_modules/@angular/material/menu/typings/menu-directive.d.ts(9,27): error TS2
307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/menu/typings/menu-directive.d.ts(16,29): error TS
2307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/menu/typings/menu-item.d.ts(8,60): error TS2307:
Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/menu/typings/menu-panel.d.ts(10,27): error TS2307
: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/menu/typings/menu-panel.d.ts(11,29): error TS2307
: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/menu/typings/menu-trigger.d.ts(1,43): error TS230
7: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/menu/typings/menu-trigger.d.ts(2,67): error TS230
7: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/menu/typings/menu-trigger.d.ts(7,43): error TS230
7: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/progress-spinner/typings/progress-spinner.d.ts(10
,26): error TS2307: Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/radio/typings/radio.d.ts(8,30): error TS2307: Can
not find module '@angular/cdk/a11y'.
node_modules/@angular/material/radio/typings/radio.d.ts(9,43): error TS2307: Can
not find module '@angular/cdk/collections'.
node_modules/@angular/material/select/typings/select.d.ts(8,44): error TS2307: C
annot find module '@angular/cdk/a11y'.
node_modules/@angular/material/select/typings/select.d.ts(9,32): error TS2307: C
annot find module '@angular/cdk/bidi'.
node_modules/@angular/material/select/typings/select.d.ts(10,32): error TS2307:
Cannot find module '@angular/cdk/collections'.
node_modules/@angular/material/select/typings/select.d.ts(11,103): error TS2307:
 Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/sidenav/typings/drawer.d.ts(9,61): error TS2307:
Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/sidenav/typings/drawer.d.ts(10,32): error TS2307:
 Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/sidenav/typings/drawer.d.ts(11,26): error TS2307:
 Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/sidenav/typings/drawer.d.ts(15,31): error TS2307:
 Cannot find module '@angular/cdk/scrolling'.
node_modules/@angular/material/slide-toggle/typings/slide-toggle.d.ts(8,30): err
or TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/slide-toggle/typings/slide-toggle.d.ts(9,26): err
or TS2307: Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/slider/typings/slider.d.ts(8,30): error TS2307: C
annot find module '@angular/cdk/a11y'.
node_modules/@angular/material/slider/typings/slider.d.ts(9,32): error TS2307: C
annot find module '@angular/cdk/bidi'.
node_modules/@angular/material/snack-bar/typings/snack-bar-config.d.ts(9,36): er
ror TS2307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/snack-bar/typings/snack-bar-config.d.ts(10,27): e
rror TS2307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/snack-bar/typings/snack-bar-container.d.ts(10,68)
: error TS2307: Cannot find module '@angular/cdk/portal'.
node_modules/@angular/material/snack-bar/typings/snack-bar-ref.d.ts(8,28): error
 TS2307: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/snack-bar/typings/snack-bar.d.ts(8,31): error TS2
307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/snack-bar/typings/snack-bar.d.ts(9,36): error TS2
307: Cannot find module '@angular/cdk/layout'.
node_modules/@angular/material/snack-bar/typings/snack-bar.d.ts(10,25): error TS
2307: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/snack-bar/typings/snack-bar.d.ts(11,31): error TS
2307: Cannot find module '@angular/cdk/portal'.
node_modules/@angular/material/sort/typings/sort-header.d.ts(9,30): error TS2307
: Cannot find module '@angular/cdk/table'.
node_modules/@angular/material/stepper/typings/step-header.d.ts(8,30): error TS2
307: Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/stepper/typings/step-label.d.ts(9,30): error TS23
07: Cannot find module '@angular/cdk/stepper'.
node_modules/@angular/material/stepper/typings/stepper-button.d.ts(1,52): error
TS2307: Cannot find module '@angular/cdk/stepper'.
node_modules/@angular/material/stepper/typings/stepper.d.ts(8,37): error TS2307:
 Cannot find module '@angular/cdk/stepper'.
node_modules/@angular/material/stepper/typings/stepper.d.ts(9,32): error TS2307:
 Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/table/typings/cell.d.ts(9,84): error TS2307: Cann
ot find module '@angular/cdk/table'.
node_modules/@angular/material/table/typings/row.d.ts(1,66): error TS2307: Canno
t find module '@angular/cdk/table'.
node_modules/@angular/material/table/typings/table-data-source.d.ts(8,28): error
 TS2307: Cannot find module '@angular/cdk/table'.
node_modules/@angular/material/table/typings/table.d.ts(1,26): error TS2307: Can
not find module '@angular/cdk/table'.
node_modules/@angular/material/tabs/typings/tab-body.d.ts(10,49): error TS2307:
Cannot find module '@angular/cdk/portal'.
node_modules/@angular/material/tabs/typings/tab-body.d.ts(11,43): error TS2307:
Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/tabs/typings/tab-header.d.ts(8,43): error TS2307:
 Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/tabs/typings/tab-header.d.ts(13,31): error TS2307
: Cannot find module '@angular/cdk/scrolling'.
node_modules/@angular/material/tabs/typings/tab-label.d.ts(9,27): error TS2307:
Cannot find module '@angular/cdk/portal'.
node_modules/@angular/material/tabs/typings/tab-nav-bar/tab-nav-bar.d.ts(8,32):
error TS2307: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/tabs/typings/tab-nav-bar/tab-nav-bar.d.ts(9,26):
error TS2307: Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/tabs/typings/tab-nav-bar/tab-nav-bar.d.ts(10,31):
 error TS2307: Cannot find module '@angular/cdk/scrolling'.
node_modules/@angular/material/tabs/typings/tab.d.ts(8,32): error TS2307: Cannot
 find module '@angular/cdk/portal'.
node_modules/@angular/material/toolbar/typings/toolbar.d.ts(10,26): error TS2307
: Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/tooltip/typings/tooltip.d.ts(9,45): error TS2307:
 Cannot find module '@angular/cdk/a11y'.
node_modules/@angular/material/tooltip/typings/tooltip.d.ts(10,32): error TS2307
: Cannot find module '@angular/cdk/bidi'.
node_modules/@angular/material/tooltip/typings/tooltip.d.ts(11,156): error TS230
7: Cannot find module '@angular/cdk/overlay'.
node_modules/@angular/material/tooltip/typings/tooltip.d.ts(12,26): error TS2307
: Cannot find module '@angular/cdk/platform'.
node_modules/@angular/material/tooltip/typings/tooltip.d.ts(13,34): error TS2307
: Cannot find module '@angular/cdk/scrolling'.
node_modules/@angular/material/tooltip/typings/tooltip.d.ts(16,53): error TS2307
: Cannot find module '@angular/cdk/layout'.


webpack: Failed to compile.

**Comment by abrahamstalin** [comment]
I have the same problem. 2018

**Comment by Chan4077** [comment]
@rahulgupta1210 @abrahamstalin Did you correctly install the dependencies? Run `npm install`.

**Comment by CWSCHREYER** [comment]
I had the same error and @factedu 's solution worked

**Comment by asmaa3107** [comment]
me toooo :

**Comment by caglarozkul** [comment]
try to instal @angular/cdk
npm -i @angular/cdk --save

**Comment by silentsnooc** [comment]
Same issue here. @chrisformula to your question [why](https://www.stilldrinking.org/programming-sucks)..

**Comment by santoshsk926** [comment]
Thank you bro @factedu. My prb solved...

**Comment by JagdishChopde20** [comment]
I was also facing same issue after installing angular7-data-table. It worked by installing the packages mentioned by  @factedu 

npm install --save @angular/material @angular/cdk

**Comment by Mutembeijoe** [comment]
I also faced this error after installing angular7-data-table. The solution by @factedu  worked perfectly for me!. I had to re-run ng serve for it to work though!
