### ISSUE TITLE
Page navigation component highlighting wrong topic

### ISSUE THREAD

**Issue by julianobrasil** [angular/material.angular.io#240]
After clicking on a topic on the float paging navigation on the right top corner of the pages (image bellow), the page is correctly scrolled so the topic is positioned at the top of the visible content area (just bellow the blue bar at the top). But the highlighted topic is different from the one you clicked on.

Bellow, I clicked on **`Unstyled Chips`**. Note that **`Theming`** is highlighted (uncorrectly), though **`Unstyled Chips`** appears at the top (correctly).

![image](https://user-images.githubusercontent.com/25405143/29871785-76937402-8d63-11e7-832b-e6772daf7d1f.png)

**Comment by donroyco** [comment]
I also noticed ( #256 ) and that one has a PR for a fix: #258

**Comment by julianobrasil** [comment]
It has been already merged to production (on Sep 7th, I think...)

Gonna close this.
