### ISSUE TITLE
I cannot read the component document on mobile, I can't scroll

### ISSUE THREAD

**Issue by tom10271** [angular/material.angular.io#247]
As titles with my iPhone 6s Plus in iOS 10.3 and latest version of Chrome

**Comment by willshowell** [comment]
This also occurs in iOS Safari and macOS Safari

**Comment by amcdnl** [comment]
Looks like its being caused by the drawers `mat-drawer-content` div.

**Comment by tom10271** [comment]
I have revisited the doc with my iPhone. I can scroll now but the font size is quite large, probably too large on mobile
