### ISSUE TITLE
[IE11] Extra scrollbar on component content

### ISSUE THREAD

**Issue by andrewseguin** [angular/material.angular.io#251]
![screenshot from 2017-09-01 10 51 10](https://user-images.githubusercontent.com/22898577/29981680-7c71102c-8f03-11e7-9ade-2a283e22dd75.png)

**Comment by jelbourn** [comment]
@mmalerba's pending sidenav change might help with this

**Comment by mmalerba** [comment]
After my change I'd like to switch our docs and demo sites to have a nice mobile friendly sidenav, I can make sure this is fixed when I do that.

**Comment by santhanam87** [comment]
Having the similar issue, any hack or fix to overcome this?

**Comment by mmalerba** [comment]
This issue has been resolved for https://material.angular.io and sidenav docs were updated with a responsive sidenav example in https://github.com/angular/material2/pull/7775
