### ISSUE TITLE
bug(docs): toc does not highlight correct item

### ISSUE THREAD

**Issue by donroyco** [angular/material.angular.io#256]
Bug.

While navigating on a [components page](https://material.angular.io/components/icon/overview) while scrolling down, the highlighted item in the *table of contents* shows correctly (below screenshot).

![toc](https://user-images.githubusercontent.com/1763537/29995175-7a9913ea-8fe3-11e7-83f5-e4bcf61cdf53.png)

Then I scroll to the end of the page and click on _Font icons with CSS_ inside the toc, I expect this item to be highlighted. However, although the page jumps to the correct section and the url has changed to [#font-icons-with-css](https://material.angular.io/components/icon/overview#font-icons-with-css), inside the toc _Icon sets_ is highlighted (below screenshot).

![wrong-toc](https://user-images.githubusercontent.com/1763537/29995214-79af3404-8fe4-11e7-9a3b-6c80d1b8b543.png)

_GIF_
![toc-gif](https://user-images.githubusercontent.com/1763537/29995490-8b3f02fc-8fea-11e7-9bf3-c39194058ea9.gif)

**Browser**
Google Chrome, version 60.0.3112.113.
In Mozilla Firefox, version 55.0.2, there is no highlighted item at all, could be related to #257 
In Apple Safari, version 10.1.1, there is no highlighted item at all, could be related to #257 

**What else?**
No errors in console.

**Comment by amcdnl** [comment]
I believe this is resolved now.
