### ISSUE TITLE
Example source code doesn't highlight

### ISSUE THREAD

**Issue by Chan4077** [angular/material.angular.io#260]
In some examples such as Dialog overview, on the _TS_ tab of the source code, the code does not highlight:
![Typescript Tab](https://user-images.githubusercontent.com/20047125/30123601-2aee0668-9365-11e7-925f-23bb0a589888.jpg)
Whereas the _HTML_ tab highlights correctly:
![HTML Tab](https://user-images.githubusercontent.com/20047125/30123724-7d337688-9365-11e7-964a-048c51c02cc7.jpg)

**Comment by donroyco** [comment]
What browser are you using?

**Comment by Chan4077** [comment]
Chrome 61.0.3163.79

**Comment by josephperrott** [comment]
I am running the same version of chrome and am seeing the syntax highlighting occuring in all three file types (ts, html and css).

Does this happen with a clean browser (clearing cache and cookies, or using an incognito window)?

**Comment by willshowell** [comment]
@josephperrott for me, it is that specific [**Dialog Overview**](https://material.angular.io/components/dialog/overview) example and only the TS file where it doesn't highlight. This is the same across browsers and using incognito.
