### ISSUE TITLE
[IE] Footer doesn't stretch to the bottom of the page

### ISSUE THREAD

**Issue by andrewseguin** [angular/material.angular.io#261]
![screenshot from 2017-09-06 13 15 19](https://user-images.githubusercontent.com/22898577/30132536-890df2e0-9305-11e7-8128-c2091fbca3f0.png)

**Comment by willshowell** [comment]
I think https://github.com/angular/material.angular.io/pull/248 covers this

**Comment by amcdnl** [comment]
@andrewseguin - Is this still an issue?

**Comment by Splaktar** [comment]
I'll try to verify this the next time that I boot up Windows. I'm pretty sure that it's fixed.

**Comment by amysorto** [comment]
Closing since IE is not supported anymore
