### ISSUE TITLE
Can't find module

### ISSUE THREAD

**Issue by jackdon** [angular/material.angular.io#266]
After I installed all packages use: `npm install` and run with: `npm start`.
Then:
```
ERROR in /Users/xulingming/Public/git_repos/material.angular.io/src/app/shared/example-
 
viewer/example-viewer.ts (5,47): Cannot find module '@angular/material-examples'.
```
After checked the package.json file, I couldn't find this package dependency was added.
It seems there is no `@angular/material-examples` package in npm registry.

**Comment by jackdon** [comment]
I found this: [https://github.com/angular/material.angular.io/pull/160](url) , solved the problem.

**Comment by hosseinGanjyar** [comment]
How you solved?
