### ISSUE TITLE
Theme not affecting the toolbar

### ISSUE THREAD

**Issue by andrewseguin** [angular/material.angular.io#272]
Changing the themes always show the toolbar as blue

![image](https://user-images.githubusercontent.com/22898577/30828698-59c017aa-a1f3-11e7-9c83-e492f4a4766f.png)

**Comment by donroyco** [comment]
@andrewseguin Is this still an issue? Works fine for me on Google Chrome 60.0.3112.113, Apple Safari 11.0, Mozilla Firefox 56.0 (64-bit) and Internet Explorer 11.

**Comment by andrewseguin** [comment]
Looks like the issue has been resolved, was verified by Jeremy but looks like it may have been a transient/caching issue
