### ISSUE TITLE
Select box is not behaving correctly as expected

### ISSUE THREAD

**Issue by amittkSharma** [angular/material.angular.io#279]
I created a mat-select in a custom dialog, but when select box is opened for making selection there is an issue in the look and feel of the select control.  Please find the screenshot
![material2selectbug](https://user-images.githubusercontent.com/9890608/31224879-f09ade7e-a9cf-11e7-8648-b7304baee4ac.PNG)
 attached.

**Comment by Chan4077** [comment]
Please create a issue [here](https://github.com/angular/material2/issues/new) instead.

**Comment by josephperrott** [comment]
Closing as this should be an issue created for angular/material rather than angular/material.angular.io
