### ISSUE TITLE
Theme changes when checking css tab for the SnackBar component

### ISSUE THREAD

**Issue by tomrcht** [angular/material.angular.io#297]
![I'm getting this behavior](https://user-images.githubusercontent.com/7870872/31711634-15dc8d94-b3f9-11e7-99df-ac9d1d260a8d.gif) on [This page](https://material.angular.io/components/snack-bar/examples) when checking the CSS tab.

This does not seems to work on another component.

Tested on Chrome 61

**Comment by willshowell** [comment]
That is kind of hilariously bizarre. Probably due to that example not having any styleUrls

https://github.com/angular/material2/tree/master/src/material-examples/snack-bar-component

**Comment by annieyw** [comment]
Seems to have been fixed. Please follow up if problem persists.
