### ISSUE TITLE
Design API docs UX

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#3]
This will cover the [type of information under "API" on the material docs site.](https://material.angularjs.org/latest/api/service/$mdDateLocaleProvider)

One "API docs" page may contain one or more classes with descriptions for each class, method, and property (potentially plus types as well). 

Components may additionally have parts of their API docs for `@Inputs` and `@Outputs` (we might just call theme properties and events)

![image](https://cloud.githubusercontent.com/assets/838736/20203247/9596ab0a-a77a-11e6-9966-4675ed86b4da.png)
(material1 version of this)

**Comment by amitafr** [comment]
![material internal page api](https://cloud.githubusercontent.com/assets/10601477/20467738/965ce6ba-af5b-11e6-8e8c-ae3e6d4bcd9b.jpg)

**Comment by jelbourn** [comment]
@amitafr I'm thinking it might be better to combine the name and type into the same column, where the type is slightly smaller underneath the name. That will give more space for description, which can be somewhat long.

We'd also need to think about how to show multiple classes under the API section, with each having its own properties and methods, inputs and outputs.
