### ISSUE TITLE
Invalidate caches on releases

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#304]
Too often we have issues with the docs seeming out-of-date or the plunkers not working because of caching issues. We should configure our build / hosting to better deal with this.

**Comment by amcdnl** [comment]
Had discussion about this with Andrew, here are the details of that convo:

> Talked to Alex - he suspects that the issue people were experiencing was due to users having an old version of the site open on their browser in a different tab. In this case, the service worker won't ever update and they'll keep seeing old content. Angular.io resolved this by forcing a refresh every 6 hours - https://github.com/angular/angular/blob/master/aio/src/app/sw-updates/sw-updates.service.ts. Fortunately, he's building out this logic directly into the CLI and it'll be a part of Angular v5. So if we wait, we can gain this benefit since our docs site is built with the CLI.

**Comment by jelbourn** [comment]
@amcdnl can you remove the service-worker bits since we're not actually using them?

**Comment by amcdnl** [comment]
Done per #305
