### ISSUE TITLE
Update Radio Button docs

### ISSUE THREAD

**Issue by chdanielmueller** [angular/material.angular.io#308]
Hi there,

I didn't get the radio buttons to work with the docs, even after changing the md- to mat-.
https://material.angular.io/components/radio/overview

Error:
```
Uncaught Error: Template parse errors:
Can't bind to 'value' since it isn't a known property of 'mat-radio-button'.
1. If 'mat-radio-button' is an Angular component and it has 'value' input, then verify that it is part of this module.
2. If 'mat-radio-button' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("nt>
  <mat-radio-group [(ngModel)]="taskType">
    <mat-radio-button *ngFor="let season of seasons" [ERROR ->][value]="season">
      {{season}}
    </mat-radio-button>
```

Could you please update the docs?

Thanks,
Daniel

**Comment by willshowell** [comment]
This is due to not importing MatRadioModule into your NgModule.

**Comment by chdanielmueller** [comment]
I did import it but it is still not working.

**Comment by amcdnl** [comment]
Closing this as its not related to the material docs website. If this issue persist, please open an issue in the material2 repo.

**Comment by michael-mckenna** [comment]
@chdanielmueller did you ever find a fix for this?

**Comment by chdanielmueller** [comment]
@michael-mckenna No, I did change the UI to a DropDown.
Don't know if this is still an issue.

**Comment by meysam-mahmoodi** [comment]
I have the same issue while I've already imported MatRadioModule into my module
