### ISSUE TITLE
Can't navigate to CDK after visiting component page.

### ISSUE THREAD

**Issue by juanlizarazo** [angular/material.angular.io#327]
1. Navigate to site's home 
2. Click the Components menu item on the top
- Notice the route is */components/categories*
3. Click on any component category option (e.g. Form Controls)
4. Click on any component (e.g. Autocomplete)
5. Click the CDK menu item on the top
- Notice how it takes you to the Components category and route stays at */components/categories*
6. Try to switch between Components and CDK by clicking their menu items on the top, route is still at */components/categories* and CDK is never displayed.

**Comment by Splaktar** [comment]
I can reproduce this easily with the current site after the 5.0.0 stable release. It certainly makes it confusing and seem like the CDK docs are broken. Some developers may not figure out how to access the docs at all after hitting this issue.
