### ISSUE TITLE
Documentation for 2.0.0-beta.8

### ISSUE THREAD

**Issue by dannyhchan** [angular/material.angular.io#332]
Hi,
Is there a way to get the documentation for previous version?  I understand that material.angular.io keeps on updating, but in a real work environment, we could not keep up to date with the latest.

Need a way to use older documentation if available.

Please advise.

**Comment by willshowell** [comment]
Not yet, no. Tracking at https://github.com/angular/material.angular.io/issues/168.

If in a pinch, you can do one of the following:
1. Navigate to the beta.8 version of the source at https://github.com/angular/material2/tree/2.0.0-beta.8. You can look at the READMEs, material-examples, and source
2. Run the docs site locally at that version (I think 46346ba should be for beta.8)

**Comment by jelbourn** [comment]
There will be a version selector eventually, but it won't capture any beta/alpha releases
