### ISSUE TITLE
HttpClientModule is missing in stackblitz MatTableModule examples

### ISSUE THREAD

**Issue by julianobrasil** [angular/material.angular.io#339]
When you open stackblitz's example in the [example's tab](https://material.angular.io/components/table/examples) => "Table retrieving data through HTTP" example, `HttpClientModule` is missing, so the example doesn't run.

![image](https://media.giphy.com/media/l2RniHFGiojwhTcQw/giphy.gif)

**Comment by Splaktar** [comment]
This is related to https://github.com/angular/material2/issues/8861. I can reproduce it. I dug around in both project's source to find the issue, but it wasn't obvious. The example was updated to use `HttpClient` in https://github.com/angular/material2/pull/6702. But it looks like something was missed somewhere.

**Comment by Splaktar** [comment]
PR is open https://github.com/angular/material.angular.io/pull/352

**Comment by colibrae** [comment]
I just want to add that I also had to add imports for HttpClientModule in my module typescript file in order to use MatIconRegistry in a component. I think the MatIconModule documentation should mention this?
