### ISSUE TITLE
Missing "material-docs-example" inside "src/assets/stackblitz"

### ISSUE THREAD

**Issue by jpmckearin** [angular/material.angular.io#340]
Last change was a few days ago in #330. It seems that I may be missing a step in the process. I am using `tools/fetch-assets-local.sh` because the [angular/material2-docs-content](https://github.com/angular/material2-docs-content) repo [no longer contains the `overview` directory](https://github.com/angular/material.angular.io/blob/89a6cf1d17a1ad63311fc607e57da8e725eb6011/tools/fetch-assets.sh#L25) that is specified in `tools/fetch-assets.sh`. (#341)

![image](https://user-images.githubusercontent.com/6679168/33460685-ea28d3a6-d5f4-11e7-8307-89b95b7001c4.png)

https://github.com/angular/material.angular.io/blob/89a6cf1d17a1ad63311fc607e57da8e725eb6011/src/assets/stackblitz/main.ts#L40

**Comment by jpmckearin** [comment]
After further investigation, it seems like this is intentional. The `stackblitz-writer` is supposed to replace the `material-docs-example` reference with the correct one at run-time.

**Comment by amcdnl** [comment]
@jpmckearin - Are you still facing this issue?
