### ISSUE TITLE
fetch-assets copies a non-existing directory from material2-docs-content

### ISSUE THREAD

**Issue by jpmckearin** [angular/material.angular.io#341]
I am not sure if the issue concerns this repo or the other one. [angular/material2-docs-content](https://github.com/angular/material2-docs-content) repo [no longer contains the `overview` directory](https://github.com/angular/material.angular.io/blob/89a6cf1d17a1ad63311fc607e57da8e725eb6011/tools/fetch-assets.sh#L25) that is specified in `tools/fetch-assets.sh`

**Comment by amcdnl** [comment]
Looks like its here to me: https://github.com/angular/material2-docs-content/tree/master/overview
