### ISSUE TITLE
sidenav example missing file

### ISSUE THREAD

**Issue by aciccarello** [angular/material.angular.io#342]
On the [sidenav example page](https://material.angular.io/components/sidenav/examples), the stackblitz does not run because it is missing the `app/button-demo.ts` file.

On the material.io site I'm seeing a 404 network error for that file.

**Comment by Splaktar** [comment]
Which example has the problem? The first one doesn't seem to have this issue.

**Comment by aciccarello** [comment]
Looks like it's working now. :tada: :ghost:
