### ISSUE TITLE
API docs missing for all Card directives but MatCard

### ISSUE THREAD

**Issue by gatimus** [angular/material.angular.io#359]

**Comment by jelbourn** [comment]
None of the card directives have an API per se, so it's captured by the overview.

**Comment by gatimus** [comment]
I originally was looking for somewhere to reference [`MatCardActions.align`](https://github.com/angular/material2/blob/master/src/lib/card/card.ts#L66) to a colleague but now I see its mentioned in the overview.
> However, the **align** property on <mat-card-actions> can be used to position the actions at the 'start' or 'end of the container.
