### ISSUE TITLE
Angular Material website is not loading

### ISSUE THREAD

**Issue by codestellar** [angular/material.angular.io#364]
The website is not showing anything.
![image](https://user-images.githubusercontent.com/17561784/34552426-5849fa46-f147-11e7-9092-dbf64dd2a460.png)

**Comment by jmaheshTrimble** [comment]
Not able to open angular material website.  Error shown "Uncaught SyntaxError: Invalid Unicode escape sequence"

**Comment by molikh** [comment]
+

**Comment by mdenissov** [comment]
Sometimes site works, sometimes it returns error 404 not found.

**Comment by mdenissov** [comment]
overview:42 GET https://material.angular.io/main.5e01746fe97ff247792f.js 404 ()

**Comment by Exac** [comment]
@mdenissov Every time this happens, refresh the page with `ctrl + F5`. 

This happens to me on both Firefox and Chrome sporadically too, and only on material.angular.io.

**Comment by xileftenurb** [comment]
seem like index.html is cached, so when a new version is uploaded, firefox/chrome keep the old version with wrong script/css version number. these are replaced with the newer version with different hash in name.

like Exac said, ctrl + F5, shift + reload or clearing cache direcly in settings will make it work.
I wonder if it could happen in any website made with angular-cli...

**Comment by amaugosomto** [comment]
ctrl + f5 on my windows and cmd + shift + R on my mac did not work for me. I have manually cleared the cache. Same issue.

**Comment by Splaktar** [comment]
This is an old issue. I just tried https://material.angular.io/ and it loaded fine for me. If you are still having issues, please open a new issue with details.

**Comment by Exac** [comment]
@Splaktar No, this issue is _still_ present. I experienced it on Firefox 87 while sharing my screen last weekend.

**Comment by Splaktar** [comment]
@Exac If you are still having issues, please open a new issue with details on how to reproduce it.
