### ISSUE TITLE
Cannot find module '@angular/material-examples'

### ISSUE THREAD

**Issue by kerby82** [angular/material.angular.io#377]
Launching the material.angular.io project with the following environment:
```
➜  material.angular.io git:(master) ✗ ng -v

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.6.6
Node: 9.3.0
OS: darwin x64
Angular: 5.2.2
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router
... service-worker

@angular/cdk: 5.1.0
@angular/cli: 1.6.6
@angular/material-moment-adapter: 5.1.0
@angular/material: 5.1.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.6
@schematics/angular: 0.1.17
typescript: 2.4.2
webpack: 3.10.0

```

I obtain the following error:
`src/app/app-module.ts(9,29): error TS2307: Cannot find module '@angular/material-examples'. src/app/pages/component-viewer/component-viewer.spec.ts(7,34): error TS2307: Cannot find module '@angular/material-examples'. src/app/shared/example-viewer/example-viewer.spec.ts(7,34): error TS2307: Cannot find module '@angular/material-examples'. src/app/shared/stackblitz/stackblitz-writer.spec.ts(8,27): error TS2307: Cannot find module '@angular/material-examples'`

**Comment by jelbourn** [comment]
Those are added by the `fetch-assets.sh` or `fetch-assets-local.sh` scripts under tools.

**Comment by s0ftimage** [comment]
fetch-assets-local.sh?  Do Windows developers matter to this group?
