### ISSUE TITLE
Angular Material Site is down

### ISSUE THREAD

**Issue by shubham-kumar** [angular/material.angular.io#378]
https://material.angular.io/ is down

console error:- ```Uncaught SyntaxError: Invalid Unicode escape sequence```

**Comment by sony-mathew** [comment]
For now you can refer :  https://material2-docs-dev.firebaseapp.com/

**Comment by Xample** [comment]
Could be related to https://github.com/angular/material.angular.io/issues/90

**Comment by jelbourn** [comment]
Should be fixed now. Our hosting provider had a transient error during deployment that caused some CDN nodes to cache an abruptly terminated JS bundle.

**Comment by kdcro101** [comment]
It works when you delete service worker https://material.angular.io but not working again on refresh

**Comment by piyanshi** [comment]
Seem site is not working today as well. 

error: 
GET https://material.angular.io/styles.34ce976a214ced57a590.css 404 ()
2components:42 GET https://material.angular.io/main.aac00e1d0efd15269264.js 404 ()

**Comment by rahultalar** [comment]
https://material.angular.io/ site is down 
![screen shot 2018-06-06 at 11 44 59 pm](https://user-images.githubusercontent.com/311559/41057085-be2f3f82-69e3-11e8-8ff9-45a75d5dc2fa.png)

**Comment by rahultalar** [comment]
Started Working

**Comment by OttoChamo** [comment]
Is down again, same result as @rahultalar screenshot

**Comment by hei-pa** [comment]
Still down

**Comment by dedicad** [comment]
Site appears to be down again...

**Comment by then3rdman** [comment]
Appears to be back up, however it did 404 a few times before it loaded successfully. Might be some serve issues?

**Comment by lukejoliat** [comment]
Down again

**Comment by lukejoliat** [comment]
material.angular.io is, of the sites I frequent for documentation, the most frequently unresponsive of all of them.

**Comment by nikhilmishra11** [comment]
I am facing the same problem.
![image](https://user-images.githubusercontent.com/22132242/42412814-465bad04-8231-11e8-8814-4cfc905cfb52.png)

**Comment by vupham-zingbox** [comment]
You can use this link as an alternate https://material2-docs-dev.firebaseapp.com/

**Comment by alex7egli** [comment]
Down again. Getting 404 for https://material.angular.io/main.a68a14a9e9191d4ee27a.js

**Comment by vupham-zingbox** [comment]
@alex7egli try to "Clear site data" in Application tab in Developer tool, the site is using Service worker and sometimes it works ... oddly

**Comment by alex7egli** [comment]
@vupham-zingbox Is there a ticket for fixing the bug that keeps taking the site down? I find this happens often and I'd like to upvote the issue.

**Comment by vupham-zingbox** [comment]
@alex7egli I'm not sure, maybe you can let me know :)

**Comment by kris-campos** [comment]
just happened to me today to

**Comment by lukejoliat** [comment]
Yeah this is ridiculous for such a popular framework.

**Comment by untilbit** [comment]
Down today for several hours. Going to rebuild the app with Vue.

**Comment by OttoChamo** [comment]
@untilbit Is up now.

**Comment by vivek081166** [comment]
https://material2-docs-dev.firebaseapp.com/
also not working
Response code 301

**Comment by vupham-zingbox** [comment]
I had to open it in incognito mode !

**Comment by vivek081166** [comment]
opening the site in "Incognito" window 
or
clearing the browser's cached data
will do the trick

**Comment by birante** [comment]
https://material2-docs-dev.firebaseapp.com/ this link is working

**Comment by dirkluijk** [comment]
Same here, last days. Seems to be a caching issue.

**Comment by rfprod** [comment]
found a link that works somewhere in similar issue https://material.angular.io/index.php

**Comment by bchoii** [comment]
Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This worked for me.

https://github.com/angular/material2/issues/12146

**Comment by chauey** [comment]
@bchoii thx, been seeing this for days. scary bug
