### ISSUE TITLE
inconsistency between examples given in documentation and style guide.

### ISSUE THREAD

**Issue by praveeno** [angular/material.angular.io#380]
**Bug, feature request, or proposal:**
_**type: - Documentation**_
inconsistency between examples given in documentation and style guide.
according to style guide [**Style 06-03**](https://angular.io/guide/styleguide#hostlistenerhostbinding-decorators-versus-host-metadata) "HostListener/HostBinding decorators versus host metadata", decorators are recommended, but in angular material website, [Directive Documentation](https://v4.angular.io/api/core/Directive) it show examples only with host metadata. 
it leads confusion.
let me know if you guys accepts this type of issues or not.
**What is the expected behavior?**
angular material documentation example should follow [angular standard style guide](https://angular.io/guide/styleguide)

**What is the current behavior?**

**What are the steps to reproduce?**

**What is the use-case or motivation for changing an existing behavior?**
standard across examples and demo.

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**

**Is there anything else we should know?**
That's all, & thanks for making web development such fun.

**Comment by amcdnl** [comment]
While I agree they should be consistent there are quite a few scenarios that those rules don't apply. I think they are meant more as guidelines rather than rules. Thanks for the feedback.
