### ISSUE TITLE
https://material.angular.io/ down - again

### ISSUE THREAD

**Issue by prjherbert** [angular/material.angular.io#381]
https://material.angular.io/ is unreachable once again.  Can we have it back please.

**Comment by Chan4077** [comment]
It's working on my end. Could it be something to do with your cache? Try clearing it. Can you also check your console in DevTools?

Also, duplicate of #378

**Comment by prjherbert** [comment]
The FetchEvent for "https://material.angular.io/" resulted in a network error response: the promise was rejected.
https://material.angular.io/ngsw-worker.js:1981 Uncaught (in promise) DOMException: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
    at Driver.handleFetch (https://material.angular.io/ngsw-worker.js:1981:15)

**Comment by Mani2693** [comment]
Same here , It works sometime and going down again and again

**Comment by kdcro101** [comment]
Same here. Page gets loaded when service worker is deleted, but nothing works except index page.

**Comment by amcdnl** [comment]
I'm not able to reproduce this. Are you all still seeing this?

**Comment by alistermada** [comment]
It was down for me as well. I got it to work on Chrome by opening  DevTools, going to Application>Service Workers then checking "Bypass for network".

**Comment by amcdnl** [comment]
@andrewseguin - Any thoughts? This could be related to SW based on the details.

**Comment by aleksandrbog** [comment]
https://material.angular.io/
This site can’t be reached

The webpage at https://material.angular.io/ might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

ping material.angular.io
PING material.angular.io (151.101.1.195) 56(84) bytes of data.
^C
--- material.angular.io ping statistics ---
7 packets transmitted, 0 received, 100% packet loss, time 6271ms

**Comment by aleksandrbog** [comment]
for google chrome 
with this configuration site is working
![material io](https://user-images.githubusercontent.com/5645725/36372305-5338a51c-156d-11e8-86bf-d16a5e01b3e8.png)

**Comment by SegesDesign** [comment]
That did the trick, thanks @aleksandrbog.
Uhm, this is a quite serious problem, I wonder why the issue has been closed without a fix (?)

**Comment by Chan4077** [comment]
@SegesDesign The service worker has already has been removed (and should be automatically unregistered when viewing the website with an outdated service worker). (See commit 63a88e199b5b96459285b2111165d1ffdd8530aa)

**Comment by SegesDesign** [comment]
Hmm, weird, well, good to know that it has been fixed. Maybe I had something cashed? Anyway, like I said the fix from aleksandrbog worked for me.
