### ISSUE TITLE
Angular Material not updated to latest version for Stackblitz

### ISSUE THREAD

**Issue by Chan4077** [angular/material.angular.io#383]
https://github.com/angular/material.angular.io/blob/427d757ad63840d5040e60909f40f2dd3e80fd94/src/app/shared/stackblitz/stackblitz-writer.ts#L24

See angular/material2#9805 for more info. The Angular Material version is fixed at this version and therefore there's no import for `MatDividerModule` which will then break the app on Stackblitz. The fix here is to just update the value. I'll try to submit a PR for this.

cc @jelbourn 

P.s. I've already submitted a PR for this. It's #386

**Comment by amcdnl** [comment]
Merged.
