### ISSUE TITLE
section links don't work until after page load

### ISSUE THREAD

**Issue by mmalerba** [angular/material.angular.io#396]
**Steps:**
Try navigating from off-site directly to a section header:
https://material.angular.io/components/input/overview#changing-when-error-messages-are-shown

**Result:**
Page loads scrolled to top.

**Expected:**
Page loads scrolled to the header I linked to.

**Notes:**
Once the page is loaded I can click header links and they work as expected.

**Comment by willshowell** [comment]
FWIW, I've previously looked into this, and it appeared to be b/c of the auto focusing.

https://github.com/angular/material.angular.io/blob/8783cfd7aa6d9da5a68c028cfe5a95c7fc3c6275/src/app/shared/navigation-focus/navigation-focus.ts#L6-L18

https://github.com/angular/material.angular.io/blob/b029f9108d4c89ce4dd75cffaaf4ea9d365dcc70/src/app/pages/component-viewer/component-viewer.ts#L46-L60

I can't recall why, but it ended up being a slightly harder problem than I anticipated.

**Comment by jelbourn** [comment]
@DevVersion would you be able to take a look at this?
