### ISSUE TITLE
Design light/dark theme toggle

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#4]
Need to be able to toggle between light and dark theme, similar to https://material2-app.firebaseapp.com/

**Comment by jelbourn** [comment]
As discussed, I want to just steal the picker from https://fonts.google.com/

**Comment by amitafr** [comment]
![material homepage toggle](https://cloud.githubusercontent.com/assets/10601477/20467734/82e1e6f8-af5b-11e6-8407-ae33d89febcd.jpg)

**Comment by jelbourn** [comment]
@amitafr I think bottom-aligning the icon make it look somewhat off. On the google fonts site, the icon is vertically centered:
![image](https://cloud.githubusercontent.com/assets/838736/20493516/00aa5ff8-afce-11e6-8ba3-33a4bfa8c1b8.png)

**Comment by amitafr** [comment]
@jelbourn thanks! Yeah the vertically centered looks more balanced 

![homepage toggle](https://cloud.githubusercontent.com/assets/10601477/20500642/49f88744-b004-11e6-9818-10c07be83bf9.jpg)

**Comment by amitafr** [comment]
Theme Colours: 
![colours](https://cloud.githubusercontent.com/assets/10601477/20940964/8e102e36-bbc2-11e6-850e-3542d224018e.png)
Cyan (500), Amber (500), Purple (700), Blue-Grey (900)

**Comment by jelbourn** [comment]
@amitafr are those primary colors or primary/accent pairs?

**Comment by JordanGS** [comment]
Was this ever made public?
