### ISSUE TITLE
Angular Material website / extra gap

### ISSUE THREAD

**Issue by javid-abd** [angular/material.angular.io#405]
BUG || not fully responsive

here is an annoying extra gap in the right side of the page.  

https://material.angular.io/components/tabs and then switch to examples.

Firefox Quantum 59.0b4 (64-bit)  (for Ubuntu)

![screenshot from 2018-03-08 00-57-09](https://user-images.githubusercontent.com/32272345/37117936-0bcfdb08-226c-11e8-8ead-83d1d4fa900b.png)

Version 64.0.3282.186 (Official Build) (64-bit)

![screenshot from 2018-03-08 00-58-50](https://user-images.githubusercontent.com/32272345/37117942-1312bb9c-226c-11e8-8ae5-fc1cab4cc8f3.png)

**Comment by Splaktar** [comment]
I'm not seeing this anymore on Firefox 59.0.2 (64-bit) or Chrome on macOS. Please re-open if this is still an issue. Looks like it got fixed though.

**Comment by javid-abd** [comment]
I checked again, I don't see it anymore. It seems it was fixed
