### ISSUE TITLE
Usability - new side nav

### ISSUE THREAD

**Issue by sjtrimble** [angular/material.angular.io#408]
**Request / Description:**
In the past I would use the expanded visible sidenav to quickly find what I was looking for, or easily explore newly added additions. Now, with the auto-collapsed new sidenav, it creates additional steps (and often guess work - especially for new learners) for users to find what they are looking for.

**Possible Recommendations:** 
- Auto-expand all items in the sidenav (the list is currently short enough for this to be ok) and/or provide a collapse-all / expand-all feature to accommodate those users who might not want the entire menu expanded.
- (Bonus Points) Create search functionality to allow a user to get to what they are searching for quickly

______________________________

**Sample Use Case:** A user arrives on the site and wants to know about Angular Material Cards and how they work.

**Current Workflow:** User expands Form Controls, Navigation, and finally Layout and finds the Cards menu.
**Ideal Workflows:** Either a) user quickly sees the card menu in the expanded menu user, b) searches (Ctrl+F) for card and finds the item on the menu, and/or c) enters the text 'card' in a search box and is recommended a page.

:)

**Comment by Splaktar** [comment]
This is indeed a pain. Thankfully it is [fixed](https://github.com/angular/material.angular.io/pull/389#issuecomment-377806712) and should be in the next docs release (probably v6).
