### ISSUE TITLE
ERROR in : Can't bind to 'displayWith' since it isn't a known property of 'mat-slider'.

### ISSUE THREAD

**Issue by andrew-morgan-0** [angular/material.angular.io#419]
Latest master build has this error: 

ng build -prod
Your global Angular CLI version (1.6.8) is greater than your local
version (1.6.7). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
Date: 2018-03-23T23:39:50.328Z
Hash: 8d6170fe424fbee1919c
Time: 12857ms
chunk {0} styles.ad2de6291359615b795d.bundle.css (styles) 70.9 kB [initial] [rendered]
chunk {1} assets/purple-green.ee480ed26020ba39116d.bundle.css (assets/purple-green) 47.3 kB [initial] [rendered]
chunk {2} assets/pink-bluegrey.c5aacdba03ab99b2b1b6.bundle.css (assets/pink-bluegrey) 47.3 kB [initial] [rendered]
chunk {3} assets/indigo-pink.1805355b9c3d50269319.bundle.css (assets/indigo-pink) 45.6 kB [initial] [rendered]
chunk {4} assets/deeppurple-amber.c1f4a16869a770b6d8a1.bundle.css (assets/deeppurple-amber) 45.9 kB [initial] [rendered]
chunk {5} main.dc3aec01b4e3441c9dfc.bundle.js (main) 84 bytes [initial] [rendered]
chunk {6} inline.be02f8f63bd82a65178b.bundle.js (inline) 1.52 kB [entry] [rendered]

ERROR in : Can't bind to 'displayWith' since it isn't a known property of 'mat-slider'.
1. If 'mat-slider' is an Angular component and it has 'displayWith' input, then verify that it is part of this module.
2. If 'mat-slider' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("<mat-slider thumbLabel [ERROR ->][displayWith]="formatLabel" tickInterval="1000" min="1" max="100000"></mat-slider>")

**Comment by Chan4077** [comment]
@andrew-morgan-0 Issues related to Angular Material should be reported at the [angular/material2](https://github.com/angular/material2) repo. This repo is meant for the documentation site.

Please close this issue.
