### ISSUE TITLE
There is no directive with "exportAs" set to "cdkTextareaAutosize" 

### ISSUE THREAD

**Issue by iexcept** [angular/material.angular.io#421]
ERROR in : There is no directive with "exportAs" set to "cdkTextareaAutosize" ("ze]="fontSize.value"><mat-label>Autosize textarea</mat-label><textarea matInput cdkTextareaAutosize [ERROR ->]#autosize="cdkTextareaAutosize" cdkAutosizeMinRows="2" cdkAutosizeMaxRo
ws="5"></textarea></mat-form-f")

**Comment by Splaktar** [comment]
I tried to reproduce this but was not able to. It looks like it was fixed. Please let us know more reproduction steps and details if this is still an issue.

**Comment by cbejensen** [comment]
For anyone else that runs into this, it happened to me because I did not have the directive on the element *and* in the ID value. Should look like this:

```html
<textarea
  cdkTextareaAutosize
  #autosize="cdkTextareaAutosize"
></textarea>
```

**Comment by singhay** [comment]
I'm facing the same error

**Comment by blin-1** [comment]
same thing

**Comment by Aman50** [comment]
I faced the same issue. Follow these steps to resolve it:

1. do `npm i @angular/cdk `
2. Now go to app.module.ts or any similar module.ts that use might be using for the component and add in imports 
`@NgModule({
  imports: [
..
TextFieldModule
..]` 
and on top of file use directory as: `import {TextFieldModule} from '@angular/cdk/text-field';`
Now, you shouldn't get this export error.
