### ISSUE TITLE
Website down - https://material.angular.io/

### ISSUE THREAD

**Issue by waqaralics** [angular/material.angular.io#423]
Angular material website goes down on first refresh.

**Important:** I see that its frequently reported and closed before. Apparently the developers might be having "disable cache" checked true on their browser settings, so that might be a reason that the error doesn't get reproduced on their PC.

**Steps to reproduce bug:**

1. Ensure you don't have "disable cache" setting enabled on your browser settings. 
2. Go to https://material.angular.io/
3. Press refresh button (not hard refresh)
4. You will see the error shown in logs below

**Workaround:**
1. Disabling cache from browser settings will let us refresh the page and still not see the error
2. Hard refreshing the site lets it run. But gives a very bad impression to users, as they might think its framework that is not stable.

**Likely cause:**
Somewhere in the code its waiting for an event that is already fired. So on the first loading it is caught and is not available for an instance after refresh if cached is not disabled.

**Logs:** 
`The FetchEvent for "https://material.angular.io/components/categories" resulted in a network error response: the promise was rejected.
ngsw-worker.js:1981 Uncaught (in promise) DOMException: Failed to execute 'waitUntil' on 'ExtendableEvent': The event handler is already finished.
    at Driver.handleFetch (https://material.angular.io/ngsw-worker.js:1981:15)
handleFetch @ ngsw-worker.js:1981
https://material.angular.io/components/categories:1 GET https://material.angular.io/components/categories net::ERR_FAILED`

**Comment by Splaktar** [comment]
I tried to reproduce this but I was unable to do so. We updated the `@angular/service-worker` version recently, are you still seeing this?

I assume you are on Chrome.
If so, go into DevTools, Application tab, then Clear Storage, select all, press "Clear site data".
Then reload a few times and see if it works.

**Comment by waqarali-softteams** [comment]
I can no longer see the problem - thanks.

Yes I am on chrome. This time  however it worked even before I cleared the site data.

Though I still cleared the site data afterwards to be sure. Thanks for your support.

**Comment by Diaaz** [comment]
The site stopped working for me in Chrome since yesterday and the workaround fixed it. Could it be because I changed networks (work to home)?

**Comment by Splaktar** [comment]
It's probably a bug with the service worker. There are a number of [open issues](https://github.com/angular/angular/issues?q=is%3Aopen+is%3Aissue+label%3A%22comp%3A+service-worker%22+label%3A%22severity3%3A+broken%22), but it sounds like  https://github.com/angular/angular/issues/20862.

**Comment by yogeshpatil143** [comment]
Dont worry about that. Please use below link its working fine

https://material2-docs-dev.firebaseapp.com/components/categories

**Comment by dirkluijk** [comment]
Same here, last days. Seems to be a caching issue.

**Comment by alexfung888** [comment]
The site fails with Chrome most of the time. The site loads fine with Edge. I guess IE is even safer, because it doesn't support service worker.

**Comment by Splaktar** [comment]
@alexfung888 please try the steps at the end of https://github.com/angular/material.angular.io/issues/423#issuecomment-383369456 in Chrome.

**Comment by yogeshpatil143** [comment]
@Splaktar its also working in Safari and Firefox too.

If not than use below link.
https://material2-docs-dev.firebaseapp.com/components/categories
