### ISSUE TITLE
error while starting the application using npm start

### ISSUE THREAD

**Issue by nrkkalyan** [angular/material.angular.io#426]
Can't bind to 'dataSource' since it isn't a known property of 'table'. ("<div class="example-container mat-elevation-z8"><table mat-table #table [ERROR ->][dataSource]="dataSource"><ng-container matColumnDef="position"><th mat-header-cell *matHeaderCellDef")

**Comment by Chan4077** [comment]
@nrkkalyan You have to install the latest version of Angular Material. Execute the following command:
```bash
npm i @angular/material@next @angular/cdk@next
```
This should install the latest `next` version (in this case, `6.0.0-rc.3`).

**Comment by Chan4077** [comment]
@gmkumar2005 Err.. the command is meant for Linux/macOS.

What did it output on Windows?

**Comment by gmkumar2005** [comment]
I have tried again today , in windows I use cmder  which can handle few unix commands. fetch-assets.sh executes properly , downloads the material2-docs-content and update the node_modules folders. 
the npm start command failed with a lot of errors starting with **ERROR in multi ./src/assets/deeppurple-amber.css** 

Given that the build depends on shell scripts I assume this project is intended to work on linux/macOs only. For now I will stick to linux

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material.angular.io/pull/434.
