### ISSUE TITLE
How to run on Windows 10 without bash?

### ISSUE THREAD

**Issue by ElderJames** [angular/material.angular.io#430]
Hey guys, I'm using Windows 10  hasn't 'bash' command,but this project seem should run the command 'npm start' with run the bash shell script. So what should I do?

**Comment by Splaktar** [comment]
There are quite a few options. Here are a couple of them:

- Old fashioned style that I've used for years (before switching to macOS): https://www.cygwin.com/
- New approach that I've never tried:
    - [Guide to Linux on Win 10](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/)
    - [MS Docs for Linux on Win 10](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

**Comment by ElderJames** [comment]
Thanks, I have tried to use Linux on Win 10, it seem that I should install the node.js environment on it.

**Comment by zhangle1** [comment]
Thank you for the problem that seems to solve my problem
