### ISSUE TITLE
Site can't be reached on Samsung Internet browser (6.4.10.5) / Chromium 56

### ISSUE THREAD

**Issue by vleput** [angular/material.angular.io#436]
### Steps to reproduce
1. Open Samsung Internet browser
2. Go to https://material.angular.io
3. Click "Refresh"
4. Message "This site can't be reached" is displayed. Further navigation on the site is impossible

Even before clicking "Refresh" if navigating to "Get Started" for example, an error message appears on the page - which makes the docs site unusable on this browser
`Failed to load document: /assets/documents/guides/material-getting-started.html. Error: Response with status: 0 for URL: null`

This seems to be related to https://github.com/angular/angular/issues/20756 and the use of @angular/service-worker package

**Comment by bschaeublin** [comment]
Can't open the site with Google Chrome too:
Version 66.0.3359.139 (official build) (64-Bit)

Error:

> The FetchEvent for "https://material.angular.io/" resulted in a network error response: the promise was rejected.
Promise.catch (async)
onFetch @ ngsw-worker.js:1901
constructor.scope.addEventListener @ ngsw-worker.js:1849
ngsw-worker.js:1988 Uncaught (in promise) TypeError: Cannot read property 'id' of undefined
    at Driver.<anonymous> (ngsw-worker.js:1988)
    at Generator.next (<anonymous>)
    at __awaiter (ngsw-worker.js:1755)
    at new Promise (<anonymous>)
    at __awaiter (ngsw-worker.js:1751)
    at Driver.updateClient (ngsw-worker.js:1985)
    at Driver.<anonymous> (ngsw-worker.js:2224)
    at Generator.next (<anonymous>)
    at fulfilled (ngsw-worker.js:1752)

**Comment by bschaeublin** [comment]
I've found following workaround for Chrome:

- Press F12 to open the developer console
- Change to the "Application" tab
- Click "Service Workers" on the left menu
- Check "Bypass for network"
- Reload the page (having the developer console opened)

I'll try to look for a permanent fix, if nobody else has the time (kinda looks like that).

**Comment by paulparas** [comment]
@bschaeublin that worked Thank you! But why wasn't it working and how did it work this way?

**Comment by Sujaydasarathi** [comment]
@bschaeublin Amazing ... it worked for me too...

**Comment by razvantomegea** [comment]
I also noticed this issue a lot of times in Chrome and Firefox. It happens when a new version of the website is deployed.

It is fixed if I clean the application cache storage from directly from **Devtools (Application > Clean site data)** or by force refreshing the page **(Ctrl + F5)**. 

The issue is **caused by ngsw-worke**r, I believe, by **not enforcing mime type** to the stored files.

**Comment by Splaktar** [comment]
This is being tracked in https://github.com/angular/angular/issues/20756. Thank you to those who posted solutions to fix this if your service worker or browser gets into a bad state.
