### ISSUE TITLE
Too much information in `<pre>` will prevent width from scaling to mobile

### ISSUE THREAD

**Issue by andrewseguin** [angular/material.angular.io#458]
One section of the docs is preventing the width of the table docs to shrink down for mobile:

```
<tr mat-header-row *matHeaderRowDef="columnsToDisplay"></tr>
<tr mat-row *matRowDef="let myRowData; columns: columnsToDisplay"></tr>
```

![1op45gmaazd](https://user-images.githubusercontent.com/22898577/40676569-f65eca9a-632f-11e8-8985-b9193190c765.png)

**Comment by Splaktar** [comment]
<img width="370" alt="Screen Shot 2021-02-06 at 4 12 03 PM" src="https://user-images.githubusercontent.com/3506071/107129792-13b5d980-6896-11eb-886d-b0e87b1f230c.png">

This has been resolved.
