### ISSUE TITLE
ng generate errors out

### ISSUE THREAD

**Issue by jffgrdnr** [angular/material.angular.io#461]
When I run ng generate I get the lovely "Unexpected token ] in JSON at position 1331" error message. 

 I started running jsonlint on each file, and the first issue is an extraneous comma "," on line 46 of angular.json. I'm still trying to get ng generate to work.

**Comment by DevVersion** [comment]
Hey, `ng generate component {NAME}` is not related to this repository. Please consider posting an issue on the `angular-cli` project.
