### ISSUE TITLE
Missing icons for existing/new components

### ISSUE THREAD

**Issue by EdricChan03** [angular/material.angular.io#463]
Some of the icons for material components are missing/not created as of now.

- [x] Badge
- [x] Bottom Sheet
- [x] Divider
- [x] Expansion Panel
- [ ] Form field (not sure for this)
- [x] Paginator
- [x] Sort header
- [x] Stepper
- [x] Table
- [x] Tree

![Component Category - Popups & Modals](https://user-images.githubusercontent.com/20047125/40897672-ee0f2f74-67ee-11e8-9e61-7988ae420a9a.png)

EDIT: I've done the icons which are available in this shared Sketch file: https://sketch.cloud/s/EGv8x

**Comment by fridoo** [comment]
What's the status on this? 

With version 10 all icons seem to be gone. I think it's a lot faster to find the right component by image than by text when scrolling through a list of 30+ components. In particular when you're not fully sure what you're looking for or when you don't know what certain components are, e.g. a snackbar.

The Material Design website is much nicer that way in terms of user experience: https://material.io/components

**Comment by EdricChan03** [comment]
I'm closing this issue as the icons have now been removed as noted by @fridoo and me in #515
