### ISSUE TITLE
https://material.angular.io/ -- This site can’t be reached

### ISSUE THREAD

**Issue by Sujaydasarathi** [angular/material.angular.io#472]
I am not able to reach the site https://material.angular.io/ for the past few days...
 Location Australia / Melbourne...

**Comment by Sujaydasarathi** [comment]
A temporary fix is available @ https://github.com/angular/material.angular.io/issues/436

Benjamin Schäublin's suggestion helped me (@bschaeublin)

**Comment by Splaktar** [comment]
What web browser? Is this still a recurring issue?

This seems like a duplicate of #436.
