### ISSUE TITLE
docs: add docs/demo-specific changelog

### ISSUE THREAD

**Issue by rusman-plat-d** [angular/material.angular.io#475]
usually I open all the documentation one by one and it is very annoying if it turns out there is no change. for that I ask to add changelog, so reader can know any changes on certain components rather than open all the pages one by one

**Comment by Chan4077** [comment]
You can view the changelog [here](https://github.com/angular/material2/blob/master/CHANGELOG.md).

**Comment by hwalyonglance** [comment]
I mean changelog about material.angular.io site. not @ angular/material package

**Comment by amysorto** [comment]
Closing this issue since most docs site changes are still related to the changes that appear in the Angular Material changelog
