### ISSUE TITLE
code style of this project in relation to Angular style guide

### ISSUE THREAD

**Issue by AnatoliKL** [angular/material.angular.io#476]
It not an issue, it is a question about style of the project.  I am using material.angular.io to learn Angular and material design. It is referenced  as an example Angular Material project in the documentation and it is indeed an excellent working example.

One thing is bothering me, it seems like code of material.angular.io does not follow Angular style guide:
 https://angular.io/guide/styleguide

Specific example , /src/app/pages/component-sidenav/component-sidenav.ts. 
This file violates "Single responsibility" style guide (multiple components are defined in the same file) and "General Naming Guidelines" (there is no "module" and "component" suffix). The same issue for all other modules/components in "pages" folder.

 There could be a very good  reason for this, I am trying to understand why.

**Comment by jelbourn** [comment]
It's a couple of things:
* The docs site is so simple that it doesn't really matter
* There are some things in the style guide I disagree with (e.g. the "component" suffix in file names).
