### ISSUE TITLE
Reason mat-toolbar isn't used to the navbar

### ISSUE THREAD

**Issue by fathert** [angular/material.angular.io#478]
Not an issue, just a question. Is there a reason why the mat-toolbar component isn't used to create the nav bar? I'm trying to create a typical nav bar as in the docs and I had thought that it should be done using the mat-toolbar but now I assume not if it's not used here.

**Comment by vdurante** [comment]
I also have the same question.

**Comment by jelbourn** [comment]
I honestly don't remember; `mat-toolbar` might not have existed in its current form back when we first made the site

**Comment by gforceg** [comment]
I have been trying for a couple hours now to create a similar navbar header using toolbar and cannot seem to get it working. Would you say that it is better to do what you've done with this app or is it likely that I'm just doing it wrong?

**Comment by fathert** [comment]
It should work, have you tried using the [CLI and schematics](https://material.angular.io/guide/schematics) to create you a working example
`ng generate @angular/material:navigation <component-name>`.

**Comment by gforceg** [comment]
I stand corrected! I had not been importing all of the necessary `Mat<Component>Module` dependencies.

**Comment by gforceg** [comment]
@fathert , I have not tried that. I will give that a shot next time.

**Comment by Splaktar** [comment]
Please remember that this repo is for issues related to the documentation site infrastructure (layout, navigation, etc). For questions about the docs content or components, please use the following:
- Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) 
- Bug reports, feature requests [here](https://github.com/angular/components/issues)
