### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by httpsOmkar** [angular/material.angular.io#484]
The tree example is not working.

![screenshot_2018-07-12 tree angular material](https://user-images.githubusercontent.com/29942725/42645060-b7e9533a-861a-11e8-9f89-23b37e14c648.png)

Getting following error in browser console.
```
ERROR TypeError: "this.getChildren(...).pipe is not a function"
```

**Comment by nicktobolski** [comment]
I'm getting an identical issue.

**Comment by httpsOmkar** [comment]
I just checked out and the site works perfectly now
