### ISSUE TITLE
Static compilation of syntax highlighting, but in Angular internals?

### ISSUE THREAD

**Issue by SamuelMarks** [angular/material.angular.io#486]
How would I rewrite [highlight-examples.sh](https://github.com/angular/material.angular.io/blob/master/tools/highlight-examples.sh) [syntax-highlight.js](https://github.com/angular/material.angular.io/blob/master/tools/syntax-highlight.js) to compile the code at the `@Component` level?

I'm wanting code highlighting, but want the examples inline; as they're only a few lines of code each. I could of course use [ngx-md](https://github.com/dimpu/ngx-md), but am curious if there's a way to natively do it at compile time in Angular.

**Comment by Splaktar** [comment]
Answered in https://github.com/angular/angular/issues/24989#issuecomment-406519150.

**Comment by SamuelMarks** [comment]
@Splaktar Okay, well in the meantime I just updated my npm package that supports markdown files in the `templateFile`.

It's just weird that what is used by Google for projects like this, is shell scripts rather than something integrateable into Angular: https://github.com/angular/material.angular.io/tree/13c76b1/tools

:\

**Comment by Splaktar** [comment]
It takes considerably more effort to write a design doc, get the feature prioritized, implement it, go through the review process, and deliver some tooling that can integrate with Angular. 

There is some talk (and a few ongoing community efforts) to better support static site generation from Markdown in the future.

I haven't had time to look into ngx-md but looks like a good option.

**Comment by SamuelMarks** [comment]
Yeah, I've seen ngx-md, it certainly fills a need, the only difference with my solution is that mine happens before compile time, so won't impact the bundle size.

I'm working on a little Rust library that takes a YAML file and produces a doc site from it. The idea being that you can have API docs in 50+ repositories, GitHub wikis, and RFCs; then generate a new doc site from them. All cross-platform, and easily integratable into a CI/CD solution.

**Comment by Splaktar** [comment]
We also have a Bazel task ([markdown-to-html](https://github.com/angular/components/tree/8.1.x/tools/markdown-to-html) that converts `.md` files to `.html` files in the `angular/components` repo before they get published to the `material2-docs-content` repo.
