### ISSUE TITLE
Issue on ipad 4

### ISSUE THREAD

**Issue by euberdeveloper** [angular/material.angular.io#488]
I use an iPad 4, iOS 10.3.3, I have a problem with the scrolling, as you can see, the page do not scroll down. So I can only read the upper part of any component or cdk page. Both safari and chrome.
![img_7753](https://user-images.githubusercontent.com/33126163/43028247-1765fd12-8c7f-11e8-8109-bcdd38c927cd.PNG)
![img_7754](https://user-images.githubusercontent.com/33126163/43028249-178cb8b2-8c7f-11e8-80c4-e7f69b9285ab.PNG)
![img_7755](https://user-images.githubusercontent.com/33126163/43028250-17ae65d4-8c7f-11e8-91c8-f0a3ddc886ea.PNG)

**Comment by Splaktar** [comment]
Unable to reproduce on an iPad 6th gen with iOS 12.3.1 on Chrome or Safari.
