### ISSUE TITLE
Error building the site

### ISSUE THREAD

**Issue by bryanjhv** [angular/material.angular.io#498]
I cloned the repository, ran the build command given in the README, and this is what happened. I see that `ScrollingModule` is only available in `@angular/cdk-experimental`, but this repository doesn't use it or even depend on it. How could I manage to build the site successfully?
Thanks in advance.

```
npm run publish-prod

> material-angular-io@0.0.0 publish-prod /home/bryan/material.angular.io
> bash ./tools/deploy.sh stable prod

> material-angular-io@0.0.0 build-themes /home/bryan/material.angular.io
> bash ./tools/build-themes.sh

Building custom theme scss files.
Finished building CSS.

Date: 2018-08-05T21:34:44.548Z
Hash: b6116c2108ee56a9d7bb
Time: 121857ms
chunk {0} runtime.a66f828dca56eeb90e02.js (runtime) 1.06 kB [entry] [rendered]
chunk {1} purple-green.dbecf5619b9ba2c0d404.css (purple-green) 44.4 kB [initial] [rendered]
chunk {2} indigo-pink.4cc8b8a52e0e3fa474a3.css (indigo-pink) 43 kB [initial] [rendered]
chunk {3} deeppurple-amber.dad821f5ee1f4d9ad1c8.css (deeppurple-amber) 42.9 kB [initial] [rendered]
chunk {4} pink-bluegrey.33919ece7d00f01aca8c.css (pink-bluegrey) 44.4 kB [initial] [rendered]
chunk {5} styles.b966cb2e09e9d54ec83b.css (styles) 64.8 kB [initial] [rendered]
chunk {6} main.b7365267315595ed5049.js (main) 130 bytes [initial] [rendered]

ERROR in : Unexpected value 'ScrollingModule in /home/bryan/material.angular.io/node_modules/@angular/cdk/scrolling.d.ts' imported by the module 'ɵhb in /home/bryan/material.angular.io/node_modules/@angular/material-examples/typings/index.d.ts'. Please add a @NgModule annotation.

Asset-group 'app' in 'ngsw-config.json' uses the 'versionedFiles' option.
As of v6 'versionedFiles' and 'files' options have the same behavior. Use 'files' instead.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-angular-io@0.0.0 publish-prod: `bash ./tools/deploy.sh stable prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the material-angular-io@0.0.0 publish-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Chan4077** [comment]
Note: You're not meant to run the `publish-prod` script. For local deployment, run `ng serve` or `npm start`.

**Comment by amalshehu** [comment]
Have the same `ScrollModule` issue.
```
ERROR in : Unexpected value 'ScrollingModule in /Users/amalshehu/C0de/material.angular.io/node_modules/@angular/cdk/scrolling.d.ts' imported by the module 'ɵhb in /Users/amalshehu/C0de/material.angular.io/node_modules/@angular/material-examples/typings/index.d.ts'. Please add a @NgModule annotation.
```

**Comment by phodal** [comment]
Have the same ScrollModule issue.

**Comment by avarteniuc** [comment]
Have the same ScrollModule issue

**Comment by secjex** [comment]
Have the same ScrollModule issue

**Comment by bryanjhv** [comment]
@Chan4077, that's not the point. The build doesn't even get to that point, and if it does, it just fails without Firebase credentials to deploy, so it's not a big deal.
For the other ones, I think it's more helpful to just like the issue instead of spamming the comments with the same thing.

Here's how I solved (temporarily) the issue. Let's first see how is that problem generated:
1. On `npm install`, the following script runs:
   https://github.com/angular/material.angular.io/blob/b34e2395b75a7aa4cad54f2e61f37b3c21ec3e2c/tools/fetch-assets.sh#L21-L37
2. It clones the latest `material2-docs-content` repository to build the `@angular/material-examples` package.
3. As that repository and `@angular/cdk` (which gets installed via NPM) are NOT in sync (i.e. version on NPM is older than repository changes), then when ScrollingModule (introduced in https://github.com/angular/material2-docs-content/commit/78420a91f024565820d560a73886c6adf1f92d50) is added, the docs app requests that code to be present, but it's not yet deployed to NPM.

So, the quick fix is:
1. Clone this repository.
2. Edit `tools/fetch-assets.sh` like this:
   ```diff
   --- a/tools/fetch-assets.sh
   +++ b/tools/fetch-assets.sh
   @@ -34,7 +34,10 @@ mkdir -p ${materialExamplesDestination}
    rm -Rf ${docsContentPath}
    
    # Clone the docs-content repository.
   -git clone ${docsContentRepoUrl} ${docsContentPath} --depth 1
   +git clone ${docsContentRepoUrl} ${docsContentPath}
   +pushd ${docsContentPath}
   +git checkout a4bc021    # 1 commit before ScrollingModule
   +popd
    
    # Copy all document assets (API, overview and guides).
    cp -R ${docsContentPath}/api ${documentsDestination}
   ```
3. `npm install` and the normal commands.

Hope it helps someone, because loading 1+ MB bundle from `angular.io` with mobile data is a real problem.

**Comment by benelliott** [comment]
@bryanjhv Thanks for the workaround, but could you reopen the issue if it is a valid bug?

**Comment by benelliott** [comment]
@bryanjhv Thanks for the workaround, but would you mind reopening this? I think it's still an issue.

Also, a simpler workaround could be to just reference the master builds of CDK and Material in `package.json`:

```
    "@angular/cdk": "github:angular/cdk-builds",
    "@angular/material": "github:angular/material2-builds",
```

**Comment by bryanjhv** [comment]
Thanks for the simpler version, I didn't know about the existence of these repositories.
Anyway, I don't think it's still an issue because that's what a repository it's meant to. Maybe the team could tag the docs repositories with the version they belong to, so one could just checkout the tag and it's done.

**Comment by benelliott** [comment]
I would say that it's still a valid issue since the project is broken if you clone and run it as per the instructions.

**Comment by JonWallsten** [comment]
Is this going to be fixed? Using the latest 7.x.x-beta for @angular/* and I can't compile due to this.

**Comment by Splaktar** [comment]
Opened PR https://github.com/angular/material.angular.io/pull/541 to resolve this.
