### ISSUE TITLE
Implement Document Viewer component

### ISSUE THREAD

**Issue by jelbourn** [angular/material.angular.io#5]
This is a component that loads a static HTML document (generated from markdown) into itself, and then dynamically loads components into that static document based on certain placeholders.

The most common placeholder will be for a live example. API docs may also be loaded this way.

**Comment by kushwahashiv** [comment]
is material.angular.io api htmls are generated from markdown. also want to know if this source code allows one to generate html files from markdown pages?

**Comment by Chan4077** [comment]
@kushwahashiv It uses `gulp-markdown` to generate the markdown with `highlight.js` for syntax highlighting the code in the markdown file and uses `gulp-transform` to transform the markdown file.

https://github.com/angular/material2/blob/c3d7cd96de6f06e1530658e41d1e8aa3ba74805e/tools/gulp/tasks/docs.ts#L75-L211
(By the way, it's available in the `material2` repo, seen [here](https://github.com/angular/material2/tree/master/tools/gulp "See gulp folder on angular/material2 on Github")

**Comment by kushwahashiv** [comment]
@Chan4077 much appreciated. Thanks for your help and explanation.
