### ISSUE TITLE
Webside down.

### ISSUE THREAD

**Issue by 1011178l** [angular/material.angular.io#501]
This site can’t be reached
The webpage at https://material.angular.io/components/sidenav/examples might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

**Comment by 1011178l** [comment]
Sorry, the webside is not down, but can't access with chrome. for IE it works.

**Comment by StefanoChiodino** [comment]
I'm using the [preview](https://material2-docs-dev.firebaseapp.com/) in the meantime. Works in Safari.

**Comment by kotyari4** [comment]
https://material.angular.io/index.php

**Comment by rehan2haque** [comment]
thanks, I've been asuming its been down for days , but jroods suggestion works for chrome.

https://material.angular.io/index.php


and earlier comment was also correct, it works in IE but not chrome.

**Comment by jelbourn** [comment]
Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This will clear the service worker cache, which persists through hard refresh.

The worker has since been removed to prevent this caching problem.
