### ISSUE TITLE
Version selector: missing versions

### ISSUE THREAD

**Issue by gfranco93** [angular/material.angular.io#502]
At the moment, the version selector in material.angular.io lets me choose between versions 5.2.5 and 6.4.5.
What about older versions (both supported and unsupported)?

**Comment by Splaktar** [comment]
Are you asking about patch versions like `6.4.4` or major versions like `4.0.0`?

Currently we only support these for the latest patch version of v5, v6, and now v7.

**Comment by Splaktar** [comment]
At this point, we don't sync tags or have any other way to sync this repo with the material2 repo which is required to serve this repo. This means that it's too hard for us to provide something like that.

It appears that we'll support the version picker from v5 going forward, but I doubt that we'll be able to go backwards to support v2 and v4.

It's possible that this repo may be moved into the primary Angular Material repo, which would make this syncing issue go away. Unfortunately, that won't help with the v2 or v4 docs 😦

**Comment by gfranco93** [comment]
Understood :ok_hand:
