### ISSUE TITLE
Documentation for CDK experimental features

### ISSUE THREAD

**Issue by djleonskennedy** [angular/material.angular.io#506]
#### Bug, feature request, or proposal:
Proposal

#### What is the expected behavior?
if experimental features available to use, would be nice to see documentation about it

#### What is the current behavior?
no documentation for experimental features 

#### What are the steps to reproduce?
https://material.angular.io/

#### What is the use-case or motivation for changing an existing behavior?
We need to use virtual-scroll, however to use experimental feature we need dive into source code

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
any

#### Is there anything else we should know?
no

**Comment by Splaktar** [comment]
This is unlikely to happen as writing docs for experimental features would often result in documenting behavior that changes within days/weeks and then the documentation would be out of date. This is why we wait for APIs to stabilize before documenting features.

In addition to the source code, you may be able to see examples of experimental features in the [demo-app](https://github.com/angular/material2/tree/master/src/demo-app).

That said, docs for [Virtual Scrolling](https://material.angular.io/cdk/scrolling/overview#virtual-scrolling) are available now that the component is available in v7.
