### ISSUE TITLE
mat-select with appearance="outline" doesn't float placeholder

### ISSUE THREAD

**Issue by popbottlepirate** [angular/material.angular.io#511]
when mat-form-field with a mat-select inside has appearance="outline" it doesn't float the placeholder when focused or with an option selected.

![image](https://user-images.githubusercontent.com/28567603/44544286-c18d9780-a6df-11e8-898b-f1244c27e5b7.png)
![image](https://user-images.githubusercontent.com/28567603/44544292-c7837880-a6df-11e8-8f2c-353b1025c6ee.png)

Take a look at this example https://stackblitz.com/edit/angular-3pubot

**Comment by josephperrott** [comment]
[Per our docs](https://material.angular.io/components/form-field/overview#form-field-appearance-variants):
>The second important difference is that the standard, fill, and outline appearances do not promote placeholders to labels. For the legacy appearance specifying <input placeholder="placeholder"> will result in a floating label being added to the mat-form-field. For the newer variants it will just add a normal placeholder to the input. If you want a floating label, add a <mat-label> to the mat-form-field.


Instead of 
```html
<mat-form-field appearance="outline">
  <mat-select placeholder="Favorite animal" [formControl]="animalControl" required>
...
```
it should be
```html
<mat-form-field appearance="outline">
  <mat-label>Favorite animal</mat-label>
  <mat-select [formControl]="animalControl" required>
...
```

**Comment by andreElrico** [comment]
I had the same problem today. I switched to "outline" after writing 100k of inputs.

Here is a regex if have come up with to help with the transition

`pattern: (?<!<[/]mat-label>\s+)<input matInput placeholder=("[^"]+")`
`sub: <mat-label>$1</mat-label>\n<input matInput`

I post this in hope it helps you. Please use at your own risk,

**Comment by brankoiliccc** [comment]
@andreElrico This looks promising. Can you please provide code snipped or example that shows how is this used. Where should we inject this pattern? 
Thanks

**Comment by Splaktar** [comment]
@andreElrico @brankoiliccc Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for docs infrastructure.
