### ISSUE TITLE
All guide pages ignore theme, background always white

### ISSUE THREAD

**Issue by JanCVanB** [angular/material.angular.io#525]
https://material.angular.io/guide/theming with a light theme selected:

<img width="730" alt="screen shot 2018-09-27 at 6 07 53 am" src="https://user-images.githubusercontent.com/4754114/46126376-86214400-c21c-11e8-8a91-f55f6f6f12db.png">

The same page with a dark theme selected:

<img width="730" alt="screen shot 2018-09-27 at 6 07 41 am" src="https://user-images.githubusercontent.com/4754114/46126385-8faaac00-c21c-11e8-967d-67d1d8fc1b95.png">

The themed-white text is unreadable on the unthemed-white background.

This is true for all guides.

Thank you for the guides!

**Comment by beeman** [comment]
Hi @JanCVanB, I was trying to reproduce the issue but it seems that it's fixed in the meanwhile.

Could you please verify if you still see the issue?

![material-theming](https://user-images.githubusercontent.com/36491/50874356-e5a9f680-13aa-11e9-8854-99d9ed5e5853.gif)

**Comment by JanCVanB** [comment]
You're right! Fixed 👍
