### ISSUE TITLE
Not able to override MAT OPTION minimum width

### ISSUE THREAD

**Issue by Hiteshnandwana** [angular/material.angular.io#526]
I am not able to override minimum width of mat-options in angular material. angular material is using  overlay. 
I tried to override minimum width using angular material CDK , But I am not able to override.
when I checked using console, I get to know that minimum width given by me is getting replace by angular material when I am opening the options.
NOTE: I am able to override minimum Height but not able to override minimum width.

my code is here

 @ViewChild('target1') target: MatSelect;

  ngAfterViewInit() {
    var dds = this.target
      dds.overlayDir.width = '60vw';      
      dds.overlayDir.minHeight = '200px';  
      dds.overlayDir.minWidth = '20px !important';    
  }

**Comment by Chan4077** [comment]
Please post this on https://github.com/angular/material2.

**Comment by Splaktar** [comment]
Yes, this repo is for the documentation site. It's not for reporting buts with components or directives. Please post an issue in the [Angular Material](https://github.com/angular/material2) repo.
