### ISSUE TITLE
Mobile layout issues with some CDK pages

### ISSUE THREAD

**Issue by Splaktar** [angular/material.angular.io#550]
This is not a great mobile experience. CDK docs only. Material docs are fine. 

No page should be horizontally scrollable and text/examples should wrap properly on mobile.

Affects
- [ ] drag and drop
- [x] bidi
- [ ] observers
- [ ] accessibility
- [ ] check for others

![screenshot_20181020-044549](https://user-images.githubusercontent.com/3506071/47273056-145ac280-d55c-11e8-8b40-eab02526fff1.png)

**Comment by HZooly** [comment]
I can take this one @Splaktar 😃

**Comment by HZooly** [comment]
@Splaktar Should I push package-lock file too ?

**Comment by Splaktar** [comment]
In relation to the above linked PRs, PR https://github.com/angular/material.angular.io/pull/657 was also needed to fix a regression with desktop layouts. We need to be careful to apply these changes only to mobile and not break desktop.

**Comment by Splaktar** [comment]
Drag and Drop Overview and Examples is working properly, but API docs have a few pixels of horizontal scroll on mobile.

Same with Observers. There is no horizontal scroll, but the tables in the API docs hit the edge of the page and the margin isn't visible.

Same for Accessibility's API docs, but it has a 1px horizontal scroll.

Hopefully with a CSS fix to the API docs layout we can resolve all of these.
