### ISSUE TITLE
theme-picker: replace use of `mat-menu` with a custom overlay

### ISSUE THREAD

**Issue by Misiu** [angular/material.angular.io#560]
As mentioned [here](https://github.com/angular/material.angular.io/blob/master/src/app/shared/theme-picker/theme-picker.html#L6) theme picker should use custom overlay.
This could be used by users as a guide when creating custom components that must have menu-like options panel.

**Comment by Splaktar** [comment]
The theme picker was significantly refactored in PR https://github.com/angular/material.angular.io/pull/697 to improve accessibility. I don't think that we have any plans at this point to convert this to a custom overlay.
