### ISSUE TITLE
Mat-menu-items navigate out of order if *ngIf is on item

### ISSUE THREAD

**Issue by qrdean** [angular/material.angular.io#577]
While testing out keyboard functionality of mat-menu we discovered the arrow navigation of mat-menu went out of order if *ngIf was on an element. 

Currently using arrow key navigation it navigates to an item in the menu without *ngIf first. Then comes back through to elements with *ngIf before wrapping back to the top.

[Stackblitz](https://stackblitz.com/edit/angular-azrs2r?file=app%2Fmenu-overview-example.html)

**Comment by calebegg** [comment]
This is https://github.com/angular/material2/issues/11652

**Comment by anbalase** [comment]
same for [*ngFor](https://stackblitz.com/edit/angular-7kfy5f?file=app/menu-overview-example.html)

**Comment by shanegilbert** [comment]
Ran into this issue also. Any update or work around?

**Comment by calebegg** [comment]
@shanegilbert See angular/material2#11652 for updates.

**Comment by Splaktar** [comment]
As explained [here](https://github.com/angular/material.angular.io/blob/master/README.md#contributing), this repo is only for reporting issues with the docs infrastructure and not for bugs with specific components.
