### ISSUE TITLE
docs(readme): instructions to build and contribute to repo are out of date

### ISSUE THREAD

**Issue by swseverance** [angular/material.angular.io#578]
README.md has the following instruction:
```
Build and copy docs and examples from Angular Material: npm run fetch-local
```
However, `package.json` has no `fetch-local` script.

**Comment by perrosen** [comment]
Was wondering the same.

**Comment by Gas-pra** [comment]
Same here

**Comment by raphael22** [comment]
@jelbourn @josephperrott @amcdnl 
Hello there, it's been 30days+ that this repo can't be build anymore with the actual readme,
just sayin...

**Comment by DooMachine** [comment]
Someone with work-around for this issue?

**Comment by MatthiasKunnen** [comment]
@DooMachine, run `yarn install` and `yarn upgrade @angular/material-examples`. The latter will make sure you have the latest [docs](https://github.com/angular/material2-docs-content).
