### ISSUE TITLE
 Failed to compile

### ISSUE THREAD

**Issue by appsteams** [angular/material.angular.io#584]
ERROR in node_modules\@angular\material-examples\examples_public_index.d.ts.ɵangular_material_src_material_examples_examples_p.html(3,9): : Property 'steps' does not exist on type 'CustomStepper'. Did you mean '_steps'?
node_modules\@angular\material-examples\examples_public_index.d.ts.ɵangular_material_src_material_examples_examples_p.html(14,7): : Property 'steps' does not exist on type 'CustomStepper'. Did you mean '_steps'?

**Comment by Raigasm** [comment]
I was hoping to contribute to this repository (by fixing some of the docs on mobile) but unfortunately I am also facing the same issue. I think this may have to do with the missing `fetch-local` npm script?

**Comment by raphael22** [comment]
@jelbourn @josephperrott @amcdnl #578 
Hello there, it's been 30days+ that this repo can't be build anymore with the actual readme,
just sayin...

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material.angular.io/commit/bd1d9ce4e63714d9b685cd11cd0280c3a48b3bc0. Sorry for the delay.
