### ISSUE TITLE
Invalid link in NPM or YARN shortcut 

### ISSUE THREAD

**Issue by Sahil624** [angular/material.angular.io#585]
Hi !
In [Getting started](https://material.angular.io/guide/getting-started) section Link on npm or yarn is broken.

Clicking on NPM or Yarn Scrolls back to Step 1.

**Comment by mahesh-kedari** [comment]
Its working fine for me.

**Comment by Splaktar** [comment]
You didn't specify which browser you were seeing this with. I can't reproduce this in Chrome 76.

As explained [here](https://github.com/angular/material.angular.io/blob/master/README.md#contributing), this repo is only for reporting issues with the docs infrastructure and not the content of the docs.

One more note, the Getting Started Guide is currently being re-written (the PR is under review).
