### ISSUE TITLE
matTooltipDisabled=false block the scroll in device

### ISSUE THREAD

**Issue by marcellokabora** [angular/material.angular.io#586]
When I set the matTooltipDisabled=false the component does not scroll anymore in devices like a phone or tablet so I switch component with a duplicate without the tooltip setup.

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). As explained [here](https://github.com/angular/material.angular.io/blob/master/README.md#contributing), this repo is only for reporting issues with the docs infrastructure.
