### ISSUE TITLE
Manifest icons don't work propery

### ISSUE THREAD

**Issue by cromefire** [angular/material.angular.io#599]
This links in your `manifest.json`:
```
"src": "\/android-chrome-36x36.png",
        ^^
```
should be more like this:
```
"src": "./android-chrome-36x36.png",
        ^^
```
because this breaks the thing in Firefox.

See https://github.com/webcompat/web-bugs/issues/30891

**Comment by marcoscaceres** [comment]
Submitted https://github.com/angular/material.angular.io/pull/601
