### ISSUE TITLE
mat dialog not working with lazy loading

### ISSUE THREAD

**Issue by dattatrey93** [angular/material.angular.io#606]
calling  dialog component from lazy loaded module component then it is not working 
Display error : "ERROR Error: No component factory found for FcmMessageComponent. Did you add it to @NgModule.entryComponents?
    at noComponentFactoryError (core.js:9877)"

But same working when calling from normal (not lazy loaded) module.

**Comment by dattatrey93** [comment]
Help me guyz. this is critical issue

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). As explained [here](https://github.com/angular/material.angular.io/blob/master/README.md#contributing), this repo is only for reporting issues with the docs infrastructure.
