### ISSUE TITLE
Strange behaviour in mat-accordion with router

### ISSUE THREAD

**Issue by mahesh-kedari** [angular/material.angular.io#610]
I am using mat-accordion with router-outlet and observing a strange behaviour. Below is a sample implementation of my use case.
https://stackblitz.com/edit/angular-material-accordion-with-router

In this example, panel 3 component and panel 4 component are having router-outlet. Now in first time navigation it works as expected. But if I collapse those panels and again try to open them I find that content of panel 4 gets reflected in panel 3.

I am not sure if its a bug or I am doing something wrong here. Can someone help me figure it out?

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). As explained [here](https://github.com/angular/material.angular.io/blob/master/README.md#contributing), this repo is only for reporting issues with the docs infrastructure.
