### ISSUE TITLE
expandion panel/accordion incorrect documentation

### ISSUE THREAD

**Issue by daddyschmack** [angular/material.angular.io#612]
The API Doc for the expansion panel looks to have a mistake.  I'm not sure what the correct options are for toggle position, as the docs say it duplicates the functionality of the `hideToggle`

@Input() hideToggle: boolean | Whether the toggle indicator should be hidden.
-- | --
@Input() togglePosition: MatAccordionTogglePosition | Whether the toggle indicator should be hidden.

**Comment by Splaktar** [comment]
I believe that his has been addressed. 

Please see [MatAccordionTogglePosition](https://material.angular.io/components/expansion/api#MatAccordionTogglePosition) for the details.

As mentioned in https://github.com/angular/material.angular.io/blob/master/README.md#contributing, please use the [angular/components](https://github.com/angular/components/issues) repo for reporting docs content issues. This repo is only for the docs infrastructure.
