### ISSUE TITLE
Version discrepancy

### ISSUE THREAD

**Issue by MatthiasKunnen** [angular/material.angular.io#613]
The version selector seems to be a bit broken. When on:

- https://material.angular.io/, 8.1.1 at time of writing, I see  
  ![image](https://user-images.githubusercontent.com/16807587/61823339-ee9c7a00-ae5b-11e9-9dbb-b0afd7090cfa.png)
  but clicking on 8.0.1 does nothing
- https://v7.material.angular.io/, I see  
  ![image](https://user-images.githubusercontent.com/16807587/61823258-bd23ae80-ae5b-11e9-9be7-a1eda7ef9a6c.png)
  but clicking on 8.0.1 redirect to https://material.angular.io/ which is 8.1.1

I checked some diffs and I believe the displayed documentation is from 8.0.1 as the changes to the docs in 8.1.0 are not currently present.

**Comment by MatthiasKunnen** [comment]
@jelbourn, pinging you since I think something is broken, hope you don't mind :)

**Comment by jelbourn** [comment]
I just pushed an update that should correct the menu. AFAICT the docs content itself is up-to-date.

**Comment by MatthiasKunnen** [comment]
> AFAICT the docs content itself is up-to-date.

**I don't think the content is up-to-date, see end of comment (sorry, it's a long one).**

@jelbourn, I'm trying to understand how changes to the readmes in [angular/components ](https://github.com/angular/components) end up appearing on https://material.angular.io.

So far I've traced it to the following steps:

1. Changes are made to readme in [angular/components](https://github.com/angular/components)
2. A new tag is created in [angular/components ](https://github.com/angular/components)
3. These changes seem to be reflected by transforming markdown to HTML into [angular/material2-docs-overview](https://github.com/angular/material2-docs-content)
4. A new version of [material.angular.io](https://github.com/angular/material.angular.io) is deployed which uses the HTML from [angular/material2-docs-overview](https://github.com/angular/material2-docs-content)

My questions are:

- Going from the commits, step 3 seems to be a manual process using some internal tool
  - I think this tool is https://github.com/angular/components/blob/master/scripts/deploy/publish-docs-content.sh, correct me if I'm wrong
  - Can this process miss changes, meaning can you somehow forget to sync material2-docs-content with the source?
  - Is this process manual? If so, can't it be automated?
- material.angular.io requires manual updates to the versions in the version list, can't this be automated? e.g. let the latest version of each major in angular/components automatically overwrite the older version in the version list
- material.angular.io seems to require a manual deploy to update its doc-content, is this the case?


The reason I'm going down this rabbit hole, apart from curiosity, is because I'm trying to follow a [PR of mine](angular/components#16463) that was recently [merged](https://github.com/angular/components/commit/2654bd1b67795afd1744e95603c7852cb2f115c6).

8.1.0 was tagged after the PR was merged. I found the related commit([2f15df9cd](https://github.com/angular/material2-docs-content/commit/2f15df9cd12beb6906583983e721bb8f3b690946)) in angular/material2-docs-content but strangely, this commit does not change the [datepicker.html file](https://github.com/angular/material2-docs-content/blob/2f15df9cd12beb6906583983e721bb8f3b690946/docs-content/overviews/material/datepicker.html) as I would expect. The change is applied in [4ff74142a3c31d4953134d73029cd6c3b7c76309](https://github.com/angular/material2-docs-content/commit/4ff74142a3c31d4953134d73029cd6c3b7c76309) which has an unrelated commit message. Why is this?

**More importantly, I'm not sure material.angular.io is currently up-to-date** since I don't see the change applied in aforementioned PR. Other changes also don't seem to be online (e.g. angular/components#16500). Can this be due to material2-docs-content being locked to 8.0.0-rc.1-b66a9a2?

https://github.com/angular/material.angular.io/blob/165af2c873776865f578c8ce53f15e64210c9625/yarn.lock#L198-L200

**Comment by MatthiasKunnen** [comment]
I've looked into this some more. Apparently, installing from a git branch when a lock file is present will install based on the ref present in the lock file. There is an open bug about this here: https://github.com/yarnpkg/yarn/issues/4734.

Whether this is the basis of the issue I'm not sure.

**Comment by jelbourn** [comment]
I just pushed it again; it should have that update now. 

It does seem like it was yarn just not pulling the updated content from the publish branch. Everything in the process is automated except for the actual deploy (the content just gets pulled in via `yarn`)

**Comment by MatthiasKunnen** [comment]
I can confirm that the docs are now up-to-date. 

Any idea why this happens?
> I found the related commit(2f15df9cd) in angular/material2-docs-content but strangely, this commit does not change the datepicker.html file as I would expect. The change is applied in 4ff74142a3c31d4953134d73029cd6c3b7c76309 which has an unrelated commit message. Why is this?

**Comment by jelbourn** [comment]
I don't remember if we push the content on every commit or on a cron job, so it might just be that
