### ISSUE TITLE
Nested functionality for mat-select

### ISSUE THREAD

**Issue by michaelb-01** [angular/material.angular.io#617]
Is there a way to have nested menus for mat-select? Similar to the nested menus in mat-menu.

I have a workaround where I'm just placing a nested mat-menu (with a hidden button) over a mat-input and opening the mat-menu when the input is clicked.. it works but feels quite hacky..

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). As explained [here](https://github.com/angular/material.angular.io/blob/master/README.md#contributing), this repo is only for reporting issues with the docs infrastructure.
