### ISSUE TITLE
keep checkbox checked while scrolling using angular virtual scroll

### ISSUE THREAD

**Issue by paco76** [angular/material.angular.io#620]
EXPECTED BEHAVIOR
keep a checkbox checked while scrolling up and down.

here is a StackBlitz [https://stackblitz.com/edit/angular-m5sh2y](https://stackblitz.com/edit/angular-m5sh2y) that demonstrate the strange behavior.

ACTION TO PERFORM ON STACKBLITZ
1. select **one name only** from the list
2. open Console
3. scroll up and down several times and observe the Console for the different values that the function creates.

EXPECTED BEHAVIOR FROM THE CODE
Console must show the selected value only! but it produces different values.

any suggestions ?

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for docs infrastructure only.
