### ISSUE TITLE
[MatRadioGroup][MatRadioButton] double *ngFor in RadioGroup (problem with event on MatRadioButton) 8 angular-material

### ISSUE THREAD

**Issue by yuralent** [angular/material.angular.io#638]
When we click on the first radioBtn and after that we will click on the next radioBtn than we didn't have the event for the second 

![radio](https://user-images.githubusercontent.com/25794155/65601929-b3c5d800-dfab-11e9-9c7f-520fe6253c1e.gif)

![radioHTML](https://user-images.githubusercontent.com/25794155/65601974-c50ee480-dfab-11e9-8725-cc6a0938ebbb.PNG)
![radioTS](https://user-images.githubusercontent.com/25794155/65601975-c50ee480-dfab-11e9-945f-4282ff8d9ced.PNG)

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for docs infrastructure only.
