### ISSUE TITLE
Switch back to open_in_new icon and remove StackBlitz icon

### ISSUE THREAD

**Issue by andrewseguin** [angular/material.angular.io#662]
The Stackblitz icon replaced the example's `open_in_new` icon. This icon is always bright blue and does not match the site theme (any of the themes), in fact it stands out as almost a "primary" button.

![XZ5upTJcZUD](https://user-images.githubusercontent.com/22898577/67238918-dad4c580-f402-11e9-9d56-99a1dc522d7e.png)

**Comment by Splaktar** [comment]
It matches the StackBlitz branding and doesn't seem to clash with any of the 4 themes supported on the site.

I'll post a PR to have it use `currentColor`.

**Comment by jelbourn** [comment]
I specially want to use the standard Material Design icon for open_in_new, which more clearly communicates what will happen. While the implementation is tied to StackBlitz now, the "open externally" idea is independent of where you're going.
