### ISSUE TITLE
beta site is usually behind latest

### ISSUE THREAD

**Issue by amitport** [angular/material.angular.io#665]
I sometimes read components' changelog and enter the beta site with hopes to see something new (`next.material.angular.io`)

Unfortunately, that site does not deploy the latest master version it is usually behind the current stable version:

latest version: `8.2.3`
`material.angular.io` version: `8.2.1`

beta version: `9.0.0-next.1`
`next.material.angular.io` version: `8.0.0-rc.0`

it would be nice if the beta version will be auto-deployed to `next.material.angular.io`
Thank you

**Comment by Splaktar** [comment]
We should have something for `9.0.0-x` up on the next site soon, but it's not quite ready just yet. We're also working on getting the latest updates to material.angular.io soon.

**Comment by Splaktar** [comment]
We just updated https://material.angular.io/ for `8.2.3`.

We've got one more PR to get in before we're ready to update https://next.material.angular.io, but we may wait until `9.0.0-rc.0`.

**Comment by Splaktar** [comment]
https://next.material.angular.io/ updated for `9.0.0-next.2`. We'll fix the dropdown that says `9.0.0-next.1` soon :)
