### ISSUE TITLE
table doesn't get populated until click on the header

### ISSUE THREAD

**Issue by Soolan** [angular/material.angular.io#683]
Hi,
I am using `Angular 8.1.3` and `material 8.2.3`.
I am trying to populate a table with data from a local json file.

I've created a service for data source:

```
// bunch of imports

@Injectable({
  providedIn: 'root'
})
export class DataService {
  constructor(private http: HttpClient) { }

  public getBooks(): Book[] {
    const book: Book[] = [];
    this.getData().subscribe(response => {
      response.forEach(item => {
        book.push({  id: item.id,  title: item.title  });
      });
    });
    return book;
  }

  public getData(): Observable<Book[]> {
    return this.http
      .get('./assets/mocks/example.json')
      .pipe( pluck('data'));
  }
}
```
and this is my book model:
```
export class Book {
  id: number;
  title: string;
}
```
Now all I need to do is to feed the data to my table component:

```
export class TableComponent implements OnInit {
  displayedColumns = ['id', 'title'];
  dataSource: MatTableDataSource<Book>;

  @ViewChild(MatPaginator, {static: true}) paginator: MatPaginator;
  @ViewChild(MatSort, {static: true}) sort: MatSort;

  constructor(private dataService: DataService) { }

  ngOnInit() {
    const books = this.dataService.getBooks();
    console.log(books); // I can see an array of book objects here
    this.dataSource = new MatTableDataSource(books);
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }
}
```

The code runs with no error, but I have to click on the table header to see the populated data.
Instead of using service, If I hard code the Book data to the `TableComponent`, it works with no problem. So the view is fine and the problem is inside the service. i.e.
```
ngOnInit() {
     // this works!
    const books = [
      {id: 1, title: 'book1'},
      {id: 2, title: 'book2'}
    ]; 
    this.dataSource = new MatTableDataSource(books);
    this.dataSource.paginator = this.paginator;
    this.dataSource.sort = this.sort;
  }
```

 To be clear I've tried loading the `paginator` and `sort` properties inside `ngAfterViewInit()` and `ngAfterContentInit()`, but neither of them worked.

I wonder if this is a bug, or if something wrong with my service.

Thank you for your thoughts and views and guides.

**Comment by Soolan** [comment]
my bad, found the issue. Plz ignore the question

**Comment by Splaktar** [comment]
I'm glad that you solved the problem. In the future, please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for docs infrastructure only.
