### ISSUE TITLE
Datepicker section input and change events is not mobile responsive.

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/material.angular.io#684]
In the date picker section of the docs. Datepicker input and change events section get out of the box because its width is set to 400px which cannot be accommodated in some mobiles.

![Datepicker   Angular Material](https://user-images.githubusercontent.com/39260684/69773757-ba461b00-11b9-11ea-8e85-e4d0a03fe9e9.png)

**Comment by ajitsinghkaler** [comment]
i've put a fix on angular/components library

**Comment by Splaktar** [comment]
Do you have the link to the PR you posted?

**Comment by ajitsinghkaler** [comment]
hey @Splaktar  here is the link https://github.com/angular/components/pull/17866 and sorry I posted it in wrong repo
