### ISSUE TITLE
On some pages the header is not taking full width

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/material.angular.io#686]
On some pages of the material.angular.io, the header is not taking full width on some screens. I've attached a screenshot for reference.

![Datepicker   Angular Material (2)](https://user-images.githubusercontent.com/39260684/70200676-3ef4e400-173a-11ea-9557-408d29f62864.png)

**Comment by Splaktar** [comment]
This is related to https://github.com/angular/material.angular.io/issues/550 which covers similar issues in the CDK.

**Comment by ajitsinghkaler** [comment]
@Splaktar so should I change my commit message

**Comment by Splaktar** [comment]
I don't think that the commit message needs to be updated at this time.

**Comment by Splaktar** [comment]
More steps to reproduce were provided [here](https://github.com/angular/material.angular.io/pull/687#issuecomment-563664926).

**Comment by Splaktar** [comment]
The issue in the screenshot here is fixed by PR https://github.com/angular/components/pull/18210.

I've also fixed a number of other related issues from https://github.com/angular/material.angular.io/issues/550 in PR https://github.com/angular/material.angular.io/pull/705.
