### ISSUE TITLE
(accessibility) - current page in the left menu only indicated with color

### ISSUE THREAD

**Issue by Wildebrew** [angular/material.angular.io#694]
In the left menu the currently selected/active page is only indicated with color, we can't [use color alone to communicate information](http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html).

To fix:
* (for sighted users) alter the class `docs-component-viewer-sidenav-item-selected` to add an icon, underline or other formatting change in addition to the color
* For a non-sighted user add the attribute `aria-current="true"` or `aria-current="page"`to the item that has the class, (the links in this case).

(do not use `aria-selected`, only `aria-current` can do the trick)

**Comment by Wildebrew** [comment]
Visually this is done really well in the overview/API/examples tabs.

**Comment by Splaktar** [comment]
Thank you for the issue report. This issue was already reported as part of https://github.com/angular/material.angular.io/issues/671.

**Comment by Wildebrew** [comment]
Hi
Yes, issue 671 was created based on an email I sent. I wasn't aware
that it had been done (my bad).
I figured it would be more managable to create separate accessibility
issues for each fix, but if you guys feel comfortable addressing issue
671 as is I'm happy not to report the remaining accessibility issues
recorded there, instead focusing on the accessibility issues with
actual components.
I'm always happy to assist/suggest fixes as needed.


On 12/27/19, Michael Prentice <notifications@github.com> wrote:
> Thank you for the issue report. This issue was already reported as part of
> https://github.com/angular/material.angular.io/issues/671.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/angular/material.angular.io/issues/694#issuecomment-569375771


-- 
Work hard. Have fun. Make history.

**Comment by Splaktar** [comment]
Yes, in the future it would be best to create separate issues. Many thanks for testing and reporting these issues. Please keep them coming 😄
