### ISSUE TITLE
(accessibility) start of overview tab content not marked for screen reader users

### ISSUE THREAD

**Issue by Wildebrew** [angular/material.angular.io#695]
Component demo pages are hard to navigate for a screen reader user. In particular it is hard to find the start of the overview content.

To fix, add `role="heading"` and `aria-level="2"` to the visually hidden `span` with the text "Overview".

```html
<span tabindex="-1" class="cdk-visually-hidden" role="heading" aria-level="2"> Overview for checkbox
</span>`
```

on [the Checkbox page](https://material.angular.io/components/checkbox/overview) (this `<span>` is present on all component demo pages).

**Comment by Splaktar** [comment]
Thank you for the report and the solution. This appears to work well. I'll put it into my current a11y branch.

**Comment by Splaktar** [comment]
PR https://github.com/angular/material.angular.io/pull/697 fixes this issue.
