### ISSUE TITLE
I cannot scroll docs' main content in safari

### ISSUE THREAD

**Issue by bromzh** [angular/material.angular.io#71]
<img width="1680" alt="2016-12-26 16 40 30" src="https://cloud.githubusercontent.com/assets/6627568/21482837/46ab8464-cb8a-11e6-97bb-c61ec4b37b20.png">
When I open any doc page, I cannot scroll right zone with content, I can scroll only left zone (with components list).

Env: macOS Sierra 10.12.2, Safari 10.0.2 (12602.3.12.0.1)

UPD. In Firefox left column (with menu list) and right column (with content) scrolls together (must scrolls separately instead).

**Comment by M4R1KU** [comment]
Same problem in older versions of chrome
Chrome 50.0.2661.87 does not work
55.0.283.87 works
