### ISSUE TITLE
Add attribute property to ng-star-inserted child created dynamically

### ISSUE THREAD

**Issue by begandroide** [angular/material.angular.io#738]
Hi, im trying to add attribute "validatorTarget" to a dynamically created `<div class="mat-form-field-underline ng-tns-c269-7 ng-star-inserted">...</div>`, in docs is not present.

I want add attribute, something like:
`<div class="mat-form-field-underline ng-tns-c269-7 ng-star-inserted" validatorTarget>...</div>`,

Exist way to perform this in a global way?

thanks in advance

**Comment by Splaktar** [comment]
Please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for docs infrastructure only.
