### ISSUE TITLE
Suggestion for pre-built themes

### ISSUE THREAD

**Issue by vazmin** [angular/material.angular.io#743]
Building themes through the shell is not friendly enough for window users.

I try to make a small modification to the angular.json, like this:

```json
"options": {
    "extractCss": true,
    "styles": [{
        "lazy": true,
        "inject": false,
        "input": "src/assets/custom-themes/pink-bluegrey.scss",
        "bundleName": "assets/pink-bluegrey"
    }]
}
```
This is more versatile and plays the same role. One theme, one file, lazy loading.

And you can import the theming this way 
`@import '~@angular/material/theming';`, 
not this way 
`@import "../../../../node_modules/@angular/material/theming";`

**Comment by Splaktar** [comment]
@vazmin you might want to take a look at [this blog post](https://dev.to/angular/angular-apps-with-a-theme-switch-like-the-ngular-material-site-darkmode-3mno) which is based on our implementation, but makes a few changes.

**Comment by Splaktar** [comment]
As for building and developing this project, the Bash shell is required. Bash is well supported on Windows in a variety of flavors (Cygwin, Git Bash, WSL, and more).

As for using `node-sass`, we do have plans to migrate this to use the `sass` package in the future.

**Comment by vazmin** [comment]
> @vazmin you might want to take a look at [this blog post](https://dev.to/angular/angular-apps-with-a-theme-switch-like-the-ngular-material-site-darkmode-3mno) which is based on our implementation, but makes a few changes.

@Splaktar Thanks, that's a great blog post.


> As for building and developing this project, the Bash shell is required. Bash is well supported on Windows in a variety of flavors (Cygwin, Git Bash, WSL, and more).

I am using wsl, he is very good, but the implementation of `bash npm --version` does not work, and export path is required. So I use `angular-cli` instead of `build-themes.sh`
