### ISSUE TITLE
Table of Contents inconsistent visibility on resize for both Components and CDK

### ISSUE THREAD

**Issue by jgladen** [angular/material.angular.io#849]
I'm using Google Chrome and looking at at Version 10.1.2

On at least some of the Components and CDK entries:
If I resize the width of the page small the TOC vanishes. Resizing the with back does not restore the TOC without a page change.

This is inconsistent with "Guides" which does.

**Comment by Splaktar** [comment]
Closed by https://github.com/angular/material.angular.io/pull/878. Also reported in https://github.com/angular/components/issues/20315.
