### ISSUE TITLE
Typo on List Document

### ISSUE THREAD

**Issue by TylerGrayStudent** [angular/material.angular.io#852]
On the page for the list component, there is a typo in the Navigation section. 
![image](https://user-images.githubusercontent.com/42650829/89673332-2bdf7880-d8b4-11ea-96d3-97ac6c8d04f1.png)

**Comment by TylerGrayStudent** [comment]
It should be used with a <mat-list-item>

**Comment by Harshi7016** [comment]
Hi @TylerGrayStudent , Could I take up this issue?

**Comment by aarzootrehan** [comment]
Hi @TylerGrayStudent , I have fixed this issue. Here is the PR for the same : 
https://github.com/angular/material2-docs-content/pull/14

**Comment by Splaktar** [comment]
What exactly do you see as the typo? The `<a mat-list-item>` is intended as the anchor element (`<a>`) should be used and the `mat-list-item` attribute is applied to it.
