### ISSUE TITLE
Doc: Material components, services, and directives link change

### ISSUE THREAD

**Issue by gkanishk** [angular/material.angular.io#870]
## Material components, services, and directives Link:
Issue:
Anchor link was not valid inside readme section.
Solution:
Replaced that with official [material directory]( https://github.com/angular/components/tree/master/src/material)

**Comment by Splaktar** [comment]
Closed by https://github.com/angular/material.angular.io/commit/38d5494244ad045e49fc25485dbdf8badf25c96a.
