### ISSUE TITLE
Material Input's border turn red based on certain condition

### ISSUE THREAD

**Issue by hanct** [angular/material.angular.io#879]
Hi,
Current Situation:  
I have a <mat-form-field> with a child matInput. Using reactive form api, i have attached a formControl to the input box, and has configured Validators.required for it.  When i clear its content in it, a border of the input box turn red, indicating that the input is invalid (not suprising, since it is a required field)

What I hope to achieve: 
I would like the border to turn red, only when the "submit button" is clicked. Cos i do not want a realtime validation, but instead prefer validation to take place only when user click the "submit button". Does angular material components provide any setting, which we can use it to specify that the border should turn red, only under certain condition.

**Comment by lashaloladze** [comment]
Hey, 
I think this issue is not angular materials issue. 
You can use FormGroup's property [**updateOn**](https://angular.io/api/forms/AbstractControl#updateOn)

`this.form = new FormGroup({
     someControl: new FormControl(),
         ...
}, { updateOn: 'submit' });`

**Comment by Splaktar** [comment]
Thank you @lashaloladze for responding to this. That appears to be the best guidance possible given that the OP did not provide a reproducible demo of the issue.

@hanct in the future, please submit Angular Material and CDK questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/components/issues). This repo is for docs infrastructure only.
