### ISSUE TITLE
'md-sidenav-layout' used in page 'component-sidenav' and cause page load error

### ISSUE THREAD

**Issue by weichen2046** [angular/material.angular.io#88]
According to the `sidenav` [README](https://github.com/angular/material2/blob/master/src/lib/sidenav/README.md) should use `md-sidenav-container` instead.

>> NOTE: The md-sidenav-layout element is deprecated. md-sidenav-container should be used instead.

[README]:https://github.com/angular/material2/blob/master/src/lib/sidenav/README.md

**Comment by andrewseguin** [comment]
Fixed in #102, thanks
