### ISSUE TITLE
Overview for Chips fails to load in Safari

### ISSUE THREAD

**Issue by chriskinzel** [angular/material.angular.io#884]
<img width="1280" alt="Screen Shot 2020-11-07 at 10 30 38 PM" src="https://user-images.githubusercontent.com/25732038/98456238-3591aa00-2149-11eb-8623-676a092066fe.png">

**Operating System**: macOS Catalina 10.15.7
**Browser**: Safari 14.0
**URL**: [https://material.angular.io/components/chips/overview](url)

### Issue
Message displayed in the Overview tab is "Failed to load document: /docs-content/overviews/material/chips/chips.html. Error: OK". All other tabs work correctly and documentation for other components works fine. The page also works fine on Chrome.

### Expected Behaviour
The overview documentation for Chips should show correctly as on Chrome.

**Comment by thomasturrell** [comment]
Opening the same page in a private window resolves the issue for me.

Some caching issue?

**Comment by chriskinzel** [comment]
Yeah not seeing this anymore, resolved now.
