### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by kblestarge** [angular/material.angular.io#90]
https://material.angular.io/ seems to be down, or something is wrong with the ssl credentials.
<img width="587" alt="screen shot 2017-01-26 at 1 05 49 pm" src="https://cloud.githubusercontent.com/assets/11730298/22348233/389f7df2-e3c8-11e6-9acb-9c68c4ea92bd.png">

**Comment by kara** [comment]
Thanks for reporting; this should have been fixed Jan 27.

**Comment by tschuegge** [comment]
We get a blank page:
<img width="438" alt="screenshot 2018-01-30 um 13 04 53" src="https://user-images.githubusercontent.com/11212275/35565554-47540cd2-05be-11e8-95d6-86f2db10a626.png">

**Comment by broec** [comment]
Blank page for me too!
![image](https://user-images.githubusercontent.com/7425401/35566066-56dcfff4-05c0-11e8-860b-fa3b2adac506.png)

**Comment by Xample** [comment]
Down again

**Comment by tonysamperi** [comment]
Same here!

**Comment by tonysamperi** [comment]
It's working now...

This is alternative version for anyone who may still pass from here
https://material2-docs-dev.firebaseapp.com/components/categories

**Comment by EreckGordon** [comment]
works for me in the usa. gitter.im noticed that it isn't working in south america (and maybe others outside usa)

**Comment by Abhijeetchakravorty** [comment]
Still does not work in India.

**Comment by aleksandrbog** [comment]
https://material.angular.io/
This site can’t be reached

The webpage at https://material.angular.io/ might be temporarily down or it may have moved permanently to a new web address.
ERR_FAILED

**Comment by Abhijeetchakravorty** [comment]
@aleksandrbog  After you land on the page. Pleas hard refresh. It will reload and render the website.

**Comment by aleksandrbog** [comment]
@Abhijeetchakravorty, thanks. After I made hard reload all works, but next day the website down too. I think it's wrong to do hard reload each time.

**Comment by tBlabs** [comment]
Not working in Poland

**Comment by Abhijeetchakravorty** [comment]
@tBlabs The problem is with the service worker. You can unregister it from the console and select the “Update on reload and Bypass for netowork checkbox”. It will render the website.

**Comment by ChrisPanthera** [comment]
Down again, in Australia, works on hard reload.

**Comment by Santoshah** [comment]
Down in India

**Comment by ziaulain** [comment]
I disconnected the internet and reconnected.. it started working.. I was also getting a blank page.

**Comment by LoveenDyall** [comment]
Still down

**Comment by elmoGrummelig** [comment]
https://material.angular.io/runtime.6afe30102d8fe7337431.js (Remote Address: 151.101.65.195:443) responds with status 404 while
https://material.angular.io/main.f239e51cfb121bce36d0.js (Remote Address: 151.101.1.195:443) return with status 200

**Comment by elmoGrummelig** [comment]
page is working again 
https://material.angular.io/runtime.6afe30102d8fe7337431.js (Remote Address: 151.101.1.195:443) responds with status 200 while

notice the address changed from 151.101.65.195:443 to 151.101.1.195:443

**Comment by isaacpitwa** [comment]
Page is Down Again

**Comment by bchoii** [comment]
Visit chrome://serviceworker-internals/ and unregister the worker for material.angular.io. This worked for me.

https://github.com/angular/material2/issues/12146

**Comment by exaland** [comment]
Hi everyone ,

I try to accessing to material.angular.io and the page show me this error message

ERR_FAILED 

Thanks for your help
