### ISSUE TITLE
Question - why have @HostBinding("class.main-content") ?

### ISSUE THREAD

**Issue by alvipeo** [angular/material.angular.io#924]
This is just not clear to me - why do you have this in the components?
```
@HostBinding("class.main-content") readonly mainContentClass = true;
```
for example, on a HomePageComponent and others. Why not just have this class in a template?

**Comment by Splaktar** [comment]
The `<app-guides>`, `<guide-viewer>`, `<app-homepage>`, and `<app-not-found>` elements are not used in any templates. They are only used by the router configuration.

**Comment by alvipeo** [comment]
ok, got it. Thanks!
