### ISSUE TITLE
material.angular.io site stuck at v12.0.0-next.3 and examples broken

### ISSUE THREAD

**Issue by joelkesler** [angular/material.angular.io#935]
When browsing the Angular Material site, you can't select v11.2.4. When I do, it reverts to v12.0.0-next.3

Also many of the examples (on the Input page) are broken :(

![image](https://user-images.githubusercontent.com/303329/111568049-a420ed00-8765-11eb-930a-00bbaebf76e4.png)

**Comment by Splaktar** [comment]
@mmalerba Fixed this a couple hours ago, sorry about the confusion. The v12 preview can be properly found at https://next.material.angular.io/ now.
