### ISSUE TITLE
Guides page on material.angular.io has two scroll bars

### ISSUE THREAD

**Issue by crisbeto** [angular/material.angular.io#945]
https://material.angular.io/guides shows two scroll bars on Windows. See the attached screenshot.

![Guides__Angular_Material_-_Google_Chrome_2021-02-14_13-44-35](https://user-images.githubusercontent.com/4450522/107877154-e2a75b80-6eca-11eb-879b-db1b234eb14c.png)

**Comment by Splaktar** [comment]
![Screen Shot 2021-04-12 at 13 10 35](https://user-images.githubusercontent.com/3506071/114434031-89893a80-9b90-11eb-8263-1f97af3eb72e.png)

I see this on Chrome on macOS as well.
