### ISSUE TITLE
Broken link to theming on getting started page

### ISSUE THREAD

**Issue by milkisevil** [angular/material.angular.io#97]
https://github.com/angular/material.angular.io/blob/master/src/assets/documents/guides/getting-started.html#L25

```html
<a href="guides/theming.md">theming guide</a>
```
should be

```html
<a href="/guide/theming">theming guide</a>
```

Also on the same line, what's the relevance of `:trident:`? If it's meant to be replaced with emoji, it's not working, instead renders as: 
![image](https://cloud.githubusercontent.com/assets/309607/22825626/51e1e34e-ef86-11e6-8df6-2b16f14ff0fb.png)

**Comment by StanFisher** [comment]
The link to the theming guide seems to be fixed now. It was fixed in: https://github.com/angular/material.angular.io/commit/537d3d667186595a5be21ec44e0f5fd60af34169.
