### ISSUE TITLE
Documentation version select drop-down broken

### ISSUE THREAD

**Issue by jljohnson001** [angular/material.angular.io#976]
https://material.angular.io/

User is unable to select documentation versions from the drop-down (browsers: Chrome, Safari, Firefox):
<img width="1414" alt="Screen Shot 2021-05-07 at 8 31 50 AM" src="https://user-images.githubusercontent.com/66479094/117457589-f9c87900-af0e-11eb-90fd-b48cc224495f.png">

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material.angular.io/commit/e55b2c9118603a4e5aa3d92ee8432a978f228cda, waiting on deployment atm.
