### ISSUE TITLE
docs-bug(guides): Cards after the second line in Guides page are misplaced

### ISSUE THREAD

**Issue by Totati** [angular/material.angular.io#986]
#### Documentation Feedback

On smaller screens cards overflow and disappear on hover
![image](https://user-images.githubusercontent.com/17689719/118127123-943a2800-b3f9-11eb-929e-e362c8dc70d3.png)

[https://material.angular.io/guides](https://material.angular.io/guides)
Microsoft Edge
Version 90.0.818.56 (Official build) (64-bit)

**Comment by Splaktar** [comment]
Some work in PR https://github.com/angular/material.angular.io/pull/985 has been started to address this, but it's still in progress.

**Comment by afnecors** [comment]
I'm working on this.

**Comment by crisbeto** [comment]
This was fixed by https://github.com/angular/material.angular.io/pull/1007.
