### ISSUE TITLE
bug(components with test harness example): Missing dependencies in StackBlitz examples

### ISSUE THREAD

**Issue by amysorto** [angular/material.angular.io#997]
#### Reproduction

This applies for the example that use test harness for all material components (except for ripples).

Steps to reproduce:
1. Open the StackBlitz link for examples that have tests using a test harness in the 'Examples' page.
 
#### Expected Behavior
A working StackBlitz link for these examples. The examples in the [documentation site for v11](https://v11.material.angular.io/) work as expected ([working example for tree component](https://v11.material.angular.io/components/tree/examples#tree-harness)).

#### Actual Behavior

The StackBlitz link for v12 documentation for test harnesses show an error ([failing example for tree component](https://material.angular.io/components/tree/examples#tree-harness)).

The error is the same for all:

```
Could not find a declaration file for module 'jasmine-core/lib/jasmine-core/jasmine.js'. '/turbo_modules/jasmine-core@3.7.1/lib/jasmine-core/jasmine.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/jasmine-core` if it exists or add a new declaration (.d.ts) file containing `declare module 'jasmine-core/lib/jasmine-core/jasmine.js';`
```

#### Environment

- Angular: ^12.0.0
- CDK/Material: ^12.0.0
- Browser(s): Chrome 90
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by Splaktar** [comment]
It looks like we need to add `@types/jasmine-core` to the following
https://github.com/angular/material.angular.io/blob/95fa5a716d98b9bd1f411cfdaa3b9b93b1806d07/src/app/shared/stack-blitz/stack-blitz-writer.ts#L94-L95

https://github.com/angular/material.angular.io/blob/95fa5a716d98b9bd1f411cfdaa3b9b93b1806d07/src/assets/stack-blitz-tests/package.json#L37
I think that we need to add `jasmine-core` to this `package.json` as well.

**Comment by Splaktar** [comment]
It wasn't that easy at all. But I have a fix in PR https://github.com/angular/material.angular.io/pull/1009.
